<a href="https://colab.research.google.com/github/varadbarclays/dev1/blob/main/ICAIF_Chunk_Ranker.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ACM ICAIF-25 AI Agentic Retrieval Grand Challenge

---

## Overview

The competition consists of two main ranking tasks:

1. **Document Ranking** – Identify and rank the five most relevant documents.  
2. **Chunk Ranking** – Identify and rank the five most relevant text chunks.

---

## Processing Pipeline

- **Data Loading**  
  Reads evaluation data from JSONL files.

- **Token Analysis**  
  Checks input size to decide whether it exceed the context length of the model..

- **Smart Ranking**  
  - *Normal cases*: Single-stage ranking.  
  - *High-token cases*: Multi-stage divide-and-conquer ranking to handle large inputs efficiently.

- **Result Compilation**  
  Combines model outputs and prepares a final CSV submission file.

---

## Output

- **kaggle_submission.csv**  
  Ready-to-submit file containing the required `sample_id` and `target_index` columns.

- **Comprehensive Statistics**  
  Summarized metrics and analysis of ranking results.

- **Top-5 Rankings**  
  Returns the five most relevant items for each query as required by the challenge.

---

## Usage

This notebook enables **end-to-end evaluation**: from loading data to generating a Kaggle-ready submission file.  
Simply run the pipeline and upload the generated `kaggle_submission.csv` to the competition platform.

In [ ]:
!pip install openai tiktoken python-dotenv pydantic tqdm

Requirement already satisfied: openai in /usr/local/lib/python3.12/dist-packages (1.109.1)
Requirement already satisfied: tiktoken in /usr/local/lib/python3.12/dist-packages (0.12.0)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (1.1.1)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (2.11.10)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.1)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai) (4.11.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.11.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.12/dist-packages (from openai) (4.15.0)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from tiktoken) (2024.11.6)
Requirement already satisfied: requests>=2.26.0 in /usr/local/lib/python3.12/dist-packages (from tiktoken) (2.32.4)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic) (0.4.2)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai) (3.10)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (2025.10.5)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken) (3.4.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken) (2.5.0)

In [ ]:
import pandas as pd
import json
import ast
import re

import asyncio
import csv
import json
import os
import traceback
from typing import Dict, List

import tiktoken
from dotenv import load_dotenv
from openai import AsyncOpenAI
from pydantic import BaseModel
from tqdm.asyncio import tqdm

load_dotenv()

False

In [ ]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"varadsrivastava","key":"07be8d5799432154520a4aff77f26a0d"}'}

In [ ]:
!ls -lha kaggle.json
!pip install -q kaggle # installing the kaggle package
!mkdir -p ~/.kaggle # creating .kaggle folder where the key should be placed
!cp kaggle.json ~/.kaggle/ # move the key to the folder
!pwd # checking the present working directory

-rw-r--r-- 1 root root 71 Oct 12 20:38 kaggle.json
/content

In [ ]:
# giving rw access (if 401-nathorized)

# !chmod 600 ~/.kaggle/kaggle.json

# Dataset

In [ ]:
!kaggle competitions download -c acm-icaif-25-ai-agentic-retrieval-grand-challenge

Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /root/.kaggle/kaggle.json'
Downloading acm-icaif-25-ai-agentic-retrieval-grand-challenge.zip to /content
 94% 1.16G/1.23G [00:01<00:00, 833MB/s]
100% 1.23G/1.23G [00:01<00:00, 1.00GB/s]

In [ ]:
!unzip *acm-icaif-25-ai-agentic-retrieval-grand-challenge.zip

Archive:  acm-icaif-25-ai-agentic-retrieval-grand-challenge.zip
  inflating: chunk_ranking_kaggle_dev.jsonl
  inflating: chunk_ranking_kaggle_eval.jsonl
  inflating: document_ranking_kaggle_dev.jsonl
  inflating: document_ranking_kaggle_eval.jsonl
  inflating: kaggle_submission.csv

# Documents

In [ ]:
file_path = '/content/document_ranking_kaggle_dev.jsonl'
data = []
with open(file_path, 'r') as f:
    for line in f:
        data.append(json.loads(line))
df_doc_dev = pd.DataFrame(data)
print(f"Head of {file_path}:")
display(df_doc_dev.head())

Head of /content/document_ranking_kaggle_dev.jsonl:

,uuid,messages,qrel
0,qe100cdf8e8f5,"[{'role': 'user', 'content': 'Rank the followi...","{'4': 1, '0': 0, '1': 0, '2': 0, '3': 0}"
1,q723817294fbe,"[{'role': 'user', 'content': 'Rank the followi...","{'4': 3, '0': 2, '1': 1, '3': 1, '2': 0}"
2,qd79970afaa57,"[{'role': 'user', 'content': 'Rank the followi...","{'4': 3, '1': 2, '0': 1, '2': 1, '3': 0}"
3,qeb144d0e9991,"[{'role': 'user', 'content': 'Rank the followi...","{'1': 3, '2': 2, '4': 1, '0': 0, '3': 0}"
4,q4f1cc6ea4ba6,"[{'role': 'user', 'content': 'Rank the followi...","{'4': 3, '2': 2, '1': 1, '0': 0, '3': 0}"

In [ ]:
df_doc_dev

,uuid,messages,qrel
0,qe100cdf8e8f5,"[{'role': 'user', 'content': 'Rank the followi...","{'4': 1, '0': 0, '1': 0, '2': 0, '3': 0}"
1,q723817294fbe,"[{'role': 'user', 'content': 'Rank the followi...","{'4': 3, '0': 2, '1': 1, '3': 1, '2': 0}"
2,qd79970afaa57,"[{'role': 'user', 'content': 'Rank the followi...","{'4': 3, '1': 2, '0': 1, '2': 1, '3': 0}"
3,qeb144d0e9991,"[{'role': 'user', 'content': 'Rank the followi...","{'1': 3, '2': 2, '4': 1, '0': 0, '3': 0}"
4,q4f1cc6ea4ba6,"[{'role': 'user', 'content': 'Rank the followi...","{'4': 3, '2': 2, '1': 1, '0': 0, '3': 0}"
...,...,...,...
4981,q30f7c8056c93,"[{'role': 'user', 'content': 'Rank the followi...","{'1': 4, '2': 3, '0': 2, '4': 1, '3': 0}"
4982,q402c59dfe9b1,"[{'role': 'user', 'content': 'Rank the followi...","{'1': 4, '0': 3, '4': 2, '3': 1, '2': 0}"
4983,q45a9a878195e,"[{'role': 'user', 'content': 'Rank the followi...","{'4': 4, '2': 3, '1': 2, '0': 1, '3': 0}"
4984,q2c57b56ff808,"[{'role': 'user', 'content': 'Rank the followi...","{'4': 4, '1': 3, '2': 2, '0': 1, '3': 0}"
4985,qe231f9f4a31c,"[{'role': 'user', 'content': 'Rank the followi...","{'1': 4, '0': 3, '4': 2, '2': 1, '3': 0}"

In [ ]:
df_doc_dev["messages"][0]

[{'role': 'user',
  'content': 'Rank the following financial document types by relevance to answer the question. Provide your ranking as a list of indices from most relevant to least relevant.\n\nQuestion: How has Agilent Technologies’ instrument reliability metric for its core diagnostics manufacturing process changed recently?\n\nDocument Types to rank:\n[Document Index 0] DEF14A\n\n[Document Index 1] 10-K\n\n[Document Index 2] 10-Q\n\n[Document Index 3] 8-K\n\n[Document Index 4] Earnings\n\nYour response must be a list of indices in exact list format (e.g., [4, 2, 1, 0, 3]), ranking every index from 0 to 4 by most relevant document type index to least relevant document type index.'}]

In [ ]:
file_path = '/content/document_ranking_kaggle_eval.jsonl'
data = []
with open(file_path, 'r') as f:
    for line in f:
        data.append(json.loads(line))
df_doc_eval = pd.DataFrame(data)
print(f"Head of {file_path}:")
display(df_doc_eval.head())

Head of /content/document_ranking_kaggle_eval.jsonl:

           _id                                           messages
0  doc_q39d7b7  [{'role': 'user', 'content': 'Rank the followi...
1  doc_q8edbb8  [{'role': 'user', 'content': 'Rank the followi...
2  doc_q060a50  [{'role': 'user', 'content': 'Rank the followi...
3  doc_q3ec868  [{'role': 'user', 'content': 'Rank the followi...
4  doc_qc7db20  [{'role': 'user', 'content': 'Rank the followi...

In [ ]:
# extract the question from df_doc_dev between "Question: " to "\n\nDocument"
df_doc_dev["question"] = df_doc_dev["messages"].apply(lambda x: x[0]["content"].split("Question: ")[1].split("\n\nDocument")[0])

df_doc_eval["question"] = df_doc_eval["messages"].apply(lambda x: x[0]["content"].split("Question: ")[1].split("\n\nDocument")[0])

In [ ]:
df_doc_dev["question"][2]

'How do sustainability or ESG considerations influence customer demand in Agilent Technologies’ market?'

In [ ]:
df_doc_eval["question"][0]

'How has Salesforce’s subscription and support segment profitability trended over recent periods?'

# Chunks

In [ ]:
file_path = '/content/chunk_ranking_kaggle_dev.jsonl'
data = []
with open(file_path, 'r') as f:
    for line in f:
        data.append(json.loads(line))
df_chunk_dev = pd.DataFrame(data)
print(f"Head of {file_path}:")
display(df_chunk_dev.head())

Head of /content/chunk_ranking_kaggle_dev.jsonl:

,uuid,messages,qrel
0,q7d7a32439929,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 0, '2': 0, '3': 0, '4': 1, '5': ..."
1,qeb144d0e9991,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 0, '2': 0, '3': 0, '4': 0, '5': ..."
2,qd79970afaa57,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 2, '2': 0, '3': 0, '4': 0, '5': ..."
3,q4f1cc6ea4ba6,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 0, '2': 0, '3': 0, '4': 0, '5': ..."
4,qc640e7d1c938,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 0, '2': 0, '3': 0, '4': 0, '5': ..."

In [ ]:
df_chunk_dev

,uuid,messages,qrel
0,q7d7a32439929,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 0, '2': 0, '3': 0, '4': 1, '5': ..."
1,qeb144d0e9991,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 0, '2': 0, '3': 0, '4': 0, '5': ..."
2,qd79970afaa57,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 2, '2': 0, '3': 0, '4': 0, '5': ..."
3,q4f1cc6ea4ba6,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 0, '2': 0, '3': 0, '4': 0, '5': ..."
4,qc640e7d1c938,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 0, '2': 0, '3': 0, '4': 0, '5': ..."
...,...,...,...
18850,q5dcbc1a08e24,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 1, '1': 2, '2': 0, '3': 0, '4': 0, '5': ..."
18851,qe231f9f4a31c,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 0, '2': 0, '3': 0, '4': 0, '5': ..."
18852,q402c59dfe9b1,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 0, '2': 0, '3': 0, '4': 1, '5': ..."
18853,q4342a9af31f9,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 0, '2': 0, '3': 0, '4': 0, '5': ..."
18854,q5dcbc1a08e24,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 0, '2': 0, '3': 0, '4': 0, '5': ..."

In [ ]:
df_chunk_dev["qrel"][0]

{'0': 0,
 '1': 0,
 '2': 0,
 '3': 0,
 '4': 1,
 '5': 0,
 '6': 0,
 '7': 0,
 '8': 2,
 '9': 0,
 '10': 0,
 '11': 0,
 '12': 0,
 '13': 0,
 '14': 0,
 '15': 0,
 '16': 0,
 '17': 0,
 '18': 0,
 '19': 0,
 '20': 0,
 '21': 0,
 '22': 0,
 '23': 0,
 '24': 2,
 '25': 0,
 '26': 0,
 '27': 0,
 '28': 0,
 '29': 0,
 '30': 0,
 '31': 0,
 '32': 0,
 '33': 0,
 '34': 0,
 '35': 0,
 '36': 0,
 '37': 0,
 '38': 0,
 '39': 0,
 '40': 0,
 '41': 0,
 '42': 1,
 '43': 0,
 '44': 0,
 '45': 0,
 '46': 0,
 '47': 0,
 '48': 0,
 '49': 0,
 '50': 0,
 '51': 0,
 '52': 0,
 '53': 0,
 '54': 0,
 '55': 0,
 '56': 0,
 '57': 0,
 '58': 0,
 '59': 0,
 '60': 0,
 '61': 0,
 '62': 0,
 '63': 0,
 '64': 2,
 '65': 0,
 '66': 0,
 '67': 0,
 '68': 0,
 '69': 0,
 '70': 0,
 '71': 0,
 '72': 0,
 '73': 0,
 '74': 0,
 '75': 0,
 '76': 0,
 '77': 0,
 '78': 0,
 '79': 0,
 '80': 0,
 '81': 0,
 '82': 0,
 '83': 0,
 '84': 0,
 '85': 0,
 '86': 0,
 '87': 0,
 '88': 0,
 '89': 0,
 '90': 0,
 '91': 0,
 '92': 0,
 '93': 0,
 '94': 0,
 '95': 0,
 '96': 0,
 '97': 0,
 '98': 0,
 '99': 0,
 '100': 0,
 '101': 0,
 '102': 0,
 '103': 0,
 '104': 0,
 '105': 0,
 '106': 0,
 '107': 0,
 '108': 0,
 '109': 0,
 '110': 0,
 '111': 0,
 '112': 0,
 '113': 0,
 '114': 0,
 '115': 0,
 '116': 0,
 '117': 0,
 '118': 0}

In [ ]:
file_path = '/content/chunk_ranking_kaggle_eval.jsonl'
data = []
with open(file_path, 'r') as f:
    for line in f:
        data.append(json.loads(line))
df_chunk_eval = pd.DataFrame(data)
print(f"Head of {file_path}:")
display(df_chunk_eval.head())

Head of /content/chunk_ranking_kaggle_eval.jsonl:

             _id                                           messages
0  chunk_q613509  [{'role': 'user', 'content': 'Identify the 10 ...
1  chunk_q83d560  [{'role': 'user', 'content': 'Identify the 10 ...
2  chunk_qc06926  [{'role': 'user', 'content': 'Identify the 10 ...
3  chunk_qaae0f2  [{'role': 'user', 'content': 'Identify the 10 ...
4  chunk_q059068  [{'role': 'user', 'content': 'Identify the 10 ...

In [ ]:
# extract the chunks from df_chunk_dev between "(best first).\n" to "\n- Put the BEST chunk"
df_chunk_dev["chunks"] = df_chunk_dev["messages"].apply(lambda x: x[0]["content"].split("(best first).\n")[1].split("\n\nTask: Select and rank")[0])

df_chunk_eval["chunks"] = df_chunk_eval["messages"].apply(lambda x: x[0]["content"].split("(best first).\n")[1].split("\n\nTask: Select and rank")[0])

In [ ]:
len(df_chunk_dev["messages"][0][0]["content"])

298154

In [ ]:
len(df_chunk_dev["chunks"][0])

297719

In [ ]:
df_chunk_dev["chunks"][0]

'Question: What share ownership guidelines are defined for Agilent Technologies’ executives and directors?\nText chunks:\n[Chunk Index 0] # UNITED STATES\nSECURITIES AND EXCHANGE COMMISSION\nWashington, D.C. 20549\n\n# SCHEDULE 14A INFORMATION\n\n# PROXY STATEMENT PURSUANT TO SECTION 14(a) OF THE\nSECURITIES EXCHANGE ACT OF 1934\n(AMENDMENT NO. )\nSCHEDULE 14A\n\nFiled by:\n[x] Filed by the Registrant\n[ ] Filed by a Party other than the Registrant\n\nCheck the appropriate box:\n[ ] Preliminary Proxy Statement\n[ ] Confidential, for Use of the Commission Only (as permitted by Rule 14a-6(e)(2))\n[x] Definitive Proxy Statement\n[ ] Definitive Additional Materials\n[ ] Soliciting Material Pursuant to §240.14a-12\n\n## AGILENT TECHNOLOGIES, INC.\n\n(Name of Registrant as Specified In Its Charter)\n\n(Name of Person(s) Filing Proxy Statement, if other than the Registrant)\n\nPayment of Filing Fee (Check the appropriate box):\n\n- No fee required.\n\n- Fee paid previously with preliminary materials.\n\n- Fee computed on table below per Exchange Act Rules 14a-6(i)(1) and 0-11.\n\nThe image shows a symmetric pattern of blue circles arranged in a star-like shape. There is a large central circle surrounded by six medium-sized circles, with smaller circles extending outward in six directions. The circles decrease in size as they radiate outward from the center.\n[Chunk Index 1] # 5301 Stevens Creek Boulevard Santa Clara, California 95051 (800) 227-9770 Notice of Annual Meeting of Stockholders\n\nTIME : 8:00 a.m., Pacific Time, on Thursday, March 14, 2024\n\nPLACE : 5301 Stevens Creek Blvd. Santa Clara, California 95051\n\nAGENDA : 1. To elect four directors to a three-year term. At the annual meeting, the Board of Directors intends to present the following nominees for election as directors:\n\n\t- Mala Anand\n\n\t- Koh Boon Hwee\n\n\t- Michael R. McMullen and\n\n\t- Daniel K. Podolsky, M.D.\n\n2. To approve, on a non-binding advisory basis, the compensation of our named executive officers.\n\n3. To ratify the Audit and Finance Committee\'s appointment of PricewaterhouseCoopers LLP as our independent registered public accounting firm.\n\n4. To vote on a stockholder proposal regarding simple majority vote.\n\n5. To consider such other business as may properly come before the annual meeting.\n\nRECORD DATE : You are entitled to vote at the annual meeting and at any adjournments, postponements or continuations thereof if you were a stockholder at the close of business on January 23, 2024.\n\nVOTING : For instructions on voting, please refer to the instructions on the Notice of Internet Availability of Proxy Materials you received in the mail or, if you received a hard copy of the proxy statement, on your enclosed proxy card.\n\nADMISSION : To attend the annual meeting, you will need to have pre-registered by 5:00 p.m., Pacific Time, on March 1, 2024. Specific instructions on pre-registration can be found in the General Information section of this proxy statement.\n\nTo be admitted to the annual meeting, you must present proof of ownership of our stock as of the record date. This can be a brokerage statement or letter from a bank or broker indicating ownership on January 23, 2024, the Notice of Internet Availability of Proxy Materials, a proxy card, or legal proxy or voting instruction card provided by your broker, bank or nominee. You may also be asked to present a form of photo identification such as a driver\'s license or passport. The annual meeting will begin promptly at 8:00 a.m., Pacific Time.\n\nWEBCAST: If you are unable to attend the annual meeting in person, you may listen through the Internet or by telephone. To listen to the live webcast, log on at www.investor.agilent.com and select the link for the webcast. To listen by telephone, please call (888) 330-2388 (international callers should dial (240) 789-2707). The meeting identification number is 87316. The webcast will begin at 8:00 a.m., Pacific Time and will remain on the company\'s website for one year. You cannot record your vote or ask questions on this website or at this phone number.\n\nBy Order of the Board of Directors\nPital\n\nP. Diana Chiu\nVice President, Interim General Counsel and Secretary\n\nThis proxy statement and the accompanying proxy card are being first sent or given to the stockholders on or about February 2, 2024.\n[Chunk Index 2] # 5301 Stevens Creek Boulevard Santa Clara, California 95051 (800) 227-9770 Notice of Annual Meeting of Stockholders (cont.)\n\nThis image shows the logo for Agilent Technologies. It features a stylized blue starburst or asterisk shape on the left, with the word "Agilent" in blue lowercase letters on the right. The design is simple and modern, using a single shade of blue on a white background.\n\n# CAUTIONARY NOTE REGARDING FORWARD-LOOKING STATEMENTS\n\nThis proxy statement contains forward-looking statements as defined in the Securities Exchange Act of 1934, as amended (the "Exchange Act") and is subject to the safe harbors created therein. The forward-looking statements contained herein are generally identified by the words "believe," "project," "expect," "anticipate," "estimate," "intend," "strategy," "future," "opportunity," "plan," "may," "should," "will," "would," "will be," "will continue," "will likely result," and similar expressions. Forward-looking statements are based on the beliefs and assumptions of our management and on currently available information. A detailed discussion of risks and uncertainties that could cause actual results and events to differ materially from such forward-looking statements is included in our annual report on Form 10-K for the fiscal year ended October 31, 2023. We undertake no responsibility to publicly update or revise any forward-looking statement.\n\n## PROXY SUMMARY\n\nThe following is a summary which highlights information contained elsewhere in this proxy statement. This summary does not contain all of the information you should consider, and you are urged to read the entire proxy statement carefully before voting.\n[Chunk Index 3] # CAUTIONARY NOTE REGARDING FORWARD-LOOKING STATEMENTS (cont.)\n\n## Voting Matters and Vote Recommendations\n\nWe currently expect to consider four items of business at the 2024 annual meeting. The following table lists those items of business and our Board\'s vote recommendation.\n\n<table><tr><th></th><th>PROPOSAL</th><th>BOARD\nRECOMMENDATION</th><th>REASONS FOR RECOMMENDATION</th><th>MORE\nINFORMATION</th></tr><tr><td>(1)</td><td>Election of four directors\nto a three-year term</td><td>FOR</td><td>The Board and the Nominating/Corporate Governance\nCommittee believe our nominees possess the skills,\nexperience and qualifications to effectively monitor\nperformance, provide oversight and support\nmanagement\'s execution of our long-term strategy.</td><td>7</td></tr><tr><td>(2)</td><td>Advisory vote to approve\nthe compensation of our\nnamed executive officers</td><td>FOR</td><td>Our executive compensation program incorporates a\nnumber of compensation governance best practices and\nreflects our commitment to pay for performance.</td><td>58</td></tr><tr><td>(3)</td><td>Ratification of the\nindependent registered\npublic accounting firm</td><td>FOR</td><td>Based on their assessment, the Board and the Audit and\nFinance Committee believe that the appointment of\nPricewaterhouseCoopers LLP is in the best interests of\nthe company and our stockholders.</td><td>59</td></tr><tr><td>(4)</td><td>Stockholder proposal\nregarding simple majority\nvote</td><td>NO\nRECOMMENDATI\nON</td><td>The Board makes no recommendation on this proposal.</td><td>62</td></tr></table>\n\n2\n\nThe image shows a blue logo for the company Agilent. The logo consists of a stylized starburst or asterisk symbol made up of white dots, positioned to the left of the company name "Agilent" in white text. The entire logo is set against a solid light blue background.\n\n# Director Nominees\n\nOur Board is currently divided into three classes serving staggered three-year terms. The following table provides summary information about each of the four director nominees who are being voted on at the annual meeting.\n\n<table><tr><th>NAME</th><th>AGE</th><th>DIRECTO\nR\nSINCE</th><th>OCCUPATION</th><th>COMMITTEE MEMBERSHIPS</th></tr><tr><td rowspan="2">Mala Anand</td><td>56</td><td>2019</td><td>Corporate Vice President, Customer\nExperience of</td><td>Compensation</td></tr><tr><td></td><td></td><td>Microsoft</td><td>Nominating/Corporate\nGovernance</td></tr><tr><td rowspan="2">Koh Boon Hwee</td><td>73</td><td>2003</td><td>Non-Executive Chairman of</td><td>Executive\nNominating/Corporate</td></tr><tr><td></td><td></td><td>Singapore Exchange Ltd.</td><td>Governance</td></tr><tr><td>Michael R. McMullen</td><td>62</td><td>2015</td><td>President &amp; Chief Executive Officer and\nDirector of\nAgilent Technologies, Inc.</td><td></td></tr><tr><td>Daniel K. Podolsky,\nM.D.</td><td>70</td><td>2015</td><td>President of the</td><td>Audit and Finance</td></tr><tr><td></td><td></td><td></td><td>University of Texas Southwestern Medical\nCenter</td><td>Nominating/Corporate\nGovernance</td></tr></table>\n[Chunk Index 4] # Director Nominees (cont.)\n\n## Corporate Governance\n\nThe Board is committed to sound and effective governance practices that it believes promote long-term stockholder value and strengthen Board and management accountability to our stockholders, customers and other stakeholders. The following table highlights many of our key governance practices. Specific details on our governance practices can be found starting on page 16.\n\n<table><tr><th></th><th>Ten of our eleven directors are independent</th><th>Annual Board self-assessment process, including peer\nevaluations</th></tr><tr><td></td><td>Independent standing Board committees</td><td>Majority voting and director resignation policy in\nuncontested director elections</td></tr><tr><td></td><td>Strong independent Chairperson</td><td>Continued assessment of highly qualified, diverse and\nindependent candidates for nomination to the Board</td></tr><tr><td></td><td>Regular meetings of our independent directors without\nmanagement present</td><td>Strong focus on pay-for-performance</td></tr><tr><td></td><td>Diverse Board with an effective mix of skills, experience\nand perspectives</td><td>Proactive stockholder engagement</td></tr><tr><td></td><td>Three new independent directors added during the past five\nyears</td><td>Policies prohibiting hedging, short selling and pledging of\nour common stock</td></tr><tr><td></td><td>Varied lengths of Board tenure with an average tenure of\nten years</td><td>Robust stock ownership guidelines for executive officers\nand directors</td></tr><tr><td></td><td>Proxy access for our stockholders</td><td>Robust enterprise risk management approach, overseen\nby the Board through its Audit and Finance Committee</td></tr></table>\n\n## Stockholder Engagement\n\nWe have a year-around stockholder engagement program that reaches a wide variety of stockholders, market participants and potential investors. This program involves periodic discussions with respect to various matters that may be of interest, such as our business, financial and operating performance, corporate governance initiatives, ESG- related disclosures and practices, diversity and inclusion topics, human capital management, risk management, compensation and corporate priorities. Feedback and perspectives from investors gathered from our engagement programs are regularly considered by our management team and Board, as the company seeks to incorporate valuable investor insights into deliberations and decision-making processes.\n\nThe image is a blank white rectangle. It appears to be an empty placeholder or frame without any content or visual elements.\n\n3\n\nThe image shows a blue rectangular logo with the word "Agilent" in white text. To the left of the text is a stylized star or burst design made up of small white dots arranged in a radial pattern. The overall design is simple and modern-looking.\n[Chunk Index 5] # Oversight of Cybersecurity Risk\n\nOur security program is based on industry standards including ISO 27002 Code of Practice, NIST and the COBIT 5 Framework. Our policies, standards and operating procedures provide a comprehensive approach to maintain the confidentiality, integrity, and availability of the data and systems in our environment in order to meet our business goals and customer needs.\n\nSecurity is a company-wide approach, and we continuously invest in our people, processes and tools to strengthen our security posture to protect both Agilent\'s and our customers\' data. This includes educating our workforce on an on- going basis of cybersecurity threats and their role in our overall security approach. All users, including our employees and third party contractors, are required to complete annual training and to confirm their understanding of and compliance with our "Acceptable Use of Information Systems Policy" to retain access to our systems.\n\nTo support our company-wide approach, we have a dedicated IT Information Security and Risk Management (ISRM) department that is accountable for the following key areas: policy, standards and operating procedures, IT compliance, IT risk management, threat and vulnerability management, security awareness and security operations, which includes comprehensive security incident management, reporting and response protocols that are tested and maintained on a regular basis. We also engage external consultants to complete independent program and capability assessments, including scanning of our systems for vulnerabilities. The head of our ISRM organization, together with our Chief Information Officer, provide periodic updates to the Audit and Finance Committee regarding our cybersecurity program, including information about cyber risk management governance and status updates on various projects intended to enhance the overall cybersecurity posture of the company.\n\n## Corporate Social Responsibility (including as to ESG Matters)\n\nWe are strongly committed to progress on environmental, social responsibility and governance issues. This commitment is an important part of our mission - to advance the quality of life - and aligned with our core business objectives. In the past year, we have continued to take proactive actions to protect the health and safety of our employees, customers, partners and suppliers. We announced our commitment to achieve net-zero greenhouse gas emissions by 2050. We believe that, with our culture of innovation, we are in a strong position to contribute important solutions to reducing greenhouse gas emissions. As a company, we are committed to continued sustainable business operations, thoughtful social responsibility initiatives and maintaining governance structures that promote effective oversight.\n[Chunk Index 6] # Oversight of Cybersecurity Risk (cont.)\n\n## Environmental Sustainability\n\nIn fiscal year 2021, we announced our commitment to achieve net-zero greenhouse gas emissions no later than 2050. To achieve these goals, we have also committed to interim greenhouse gas reduction targets. By 2030, we aim to reduce absolute scope 1 and 2 emissions by 50% and scope 3 emissions by at least 30% (with a stretch goal of 40%) from a base year of 2019. In addition, we plan to continue to invest in renewable energy and focus on three areas where our carbon footprint is greatest: purchased goods and services, sold products, and transportation and distribution. As part of our climate action plan, we have established near and long-term emission reduction targets to limit planetary warming to 1.5°C above pre-industrial levels which have been approved by the Science Based Targets initiative ("SBTi"). To provide investors with meaningful sustainability information, we also announced that we are adopting the Task Force on Climate-related Financial Disclosures (TCFD) recommendations for disclosing climate- related risks, alongside our reporting in accordance with SASB and GRI.\n\n## Diversity and Inclusion\n\nAs a global company, much of our success is rooted in the diversity of our teams and our commitment to inclusion. We value diversity at all levels and continue to focus on extending our diversity and inclusion initiatives across our entire workforce, from providing managers transparency of their workforce pay equity to working with managers to develop strategies for building diverse teams and promoting the advancement of leaders from different backgrounds. Agilent is committed to creating a diverse work environment and is proud to be an equal opportunity employer. We believe in an inclusive workforce, where employees from a number of cultures and countries are engaged and encouraged to leverage their collective talents. As of October 31, 2023, approximately 38% of our full-time employees were female. Approximately 42% of our board is comprised of directors representing traditionally underrepresented groups as of December 31, 2023. We also have launched a number of company-wide initiatives including employee- network groups aimed at promoting engagement of women, Black, LGBTQIA+, Asian, and Hispanic and Latino employees. To further our commitment to global diversity and inclusion efforts, in 2020 we hired an associate vice president of diversity and inclusion and launched a number of company-wide initiatives.\n\n4\n\nThe image shows a corporate logo on a blue background. The logo consists of a stylized white starburst or sparkle design next to the word "Agilent" in white capital letters. This appears to be the logo for Agilent Technologies, a scientific instrumentation and laboratory services company.\n[Chunk Index 7] # Oversight and Management of Corporate Social Responsibility (including as to ESG Matters)\n\nOur Board, through its Nominating/Corporate Governance Committee, oversees Agilent\'s environmental, social and governance (ESG) program and the progress of our ESG efforts and initiatives. The Nominating/Corporate Governance Committee formally reviews our ESG efforts, including our sustainability initiatives, within the organization and reports to the Board on a regular basis. The Nominating/Corporate Governance Committee charter is located in the Investor Relations section of our website and can be accessed by clicking on "Committee Charters" or "Governance Documents" in the "Governance" section of our investor relations web page at www.investor.agilent.com The Board and its Compensation Committee oversee the administration of the company\'s employee benefits, including health and compensation plans.\n\nFor more information, refer to our annual Environmental, Social and Governance report, which is available on our website. Our Environmental, Social and Governance report and website are not part of or incorporated by reference into this proxy statement.\n\n5\n\nThe image shows a stylized snowflake or star shape in white on a blue background. The design consists of six main arms radiating outward from a central point. Each arm has smaller branches or points extending from it, creating a symmetrical and intricate pattern.\n[Chunk Index 8] # 2024 ANNUAL MEETING OF STOCKHOLDERS NOTICE OF ANNUAL MEETING AND PROXY STATEMENT TABLE OF CONTENTS\n\n<table><tr><th></th><th>Page</th></tr><tr><td>PROPOSAL 1 - ELECTION OF DIRECTORS</td><td>7</td></tr><tr><td>Director Nominees for Election to New Three-Year Terms That Will Expire in 2027</td><td>8</td></tr><tr><td>Directors Whose Terms Expire in 2025</td><td>10</td></tr><tr><td>Directors Whose Terms Expire in 2026</td><td>12</td></tr><tr><td>COMPENSATION OF NON-EMPLOYEE DIRECTORS</td><td>14</td></tr><tr><td>Summary of Non-Employee Director Annual Compensation for the 2023 Plan Year</td><td>14</td></tr><tr><td>Non-Employee Director Compensation for Fiscal Year 2023</td><td>15</td></tr><tr><td>Non-Employee Director Reimburs

In [ ]:
df_chunk_dev["messages"][0]

[{'role': 'user',

In [ ]:
# df_chunk_eval["chunks"][5]

In [ ]:
df_chunk_dev

,uuid,messages,qrel,chunks
0,q7d7a32439929,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 0, '2': 0, '3': 0, '4': 1, '5': ...",Question: What share ownership guidelines are ...
1,qeb144d0e9991,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 0, '2': 0, '3': 0, '4': 0, '5': ...",Question: What exposure does Agilent Technolog...
2,qd79970afaa57,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 2, '2': 0, '3': 0, '4': 0, '5': ...",Question: How do sustainability or ESG conside...
3,q4f1cc6ea4ba6,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 0, '2': 0, '3': 0, '4': 0, '5': ...",Question: What sentiment trends are visible ar...
4,qc640e7d1c938,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 0, '2': 0, '3': 0, '4': 0, '5': ...",Question: What did Agilent Technologies’ execu...
...,...,...,...,...
18850,q5dcbc1a08e24,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 1, '1': 2, '2': 0, '3': 0, '4': 0, '5': ...",Question: What was the level of Zoetis Inc.’s ...
18851,qe231f9f4a31c,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 0, '2': 0, '3': 0, '4': 0, '5': ...",Question: How are talent retention or workforc...
18852,q402c59dfe9b1,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 0, '2': 0, '3': 0, '4': 1, '5': ...",Question: What themes have investors highlight...
18853,q4342a9af31f9,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 0, '2': 0, '3': 0, '4': 0, '5': ...",Question: What guidance was offered regarding ...
18854,q5dcbc1a08e24,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 0, '2': 0, '3': 0, '4': 0, '5': ...",Question: What was the level of Zoetis Inc.’s ...

In [ ]:
print(len(df_chunk_eval), len(df_chunk_eval["_id"].unique()))

200 200

In [ ]:
# Create a counter for each unique UUID
uuid_counts = {}
new_uuids = []

for uuid in df_chunk_dev['uuid']:
    if uuid not in uuid_counts:
        uuid_counts[uuid] = 0
        new_uuids.append(f"{uuid}_doc{uuid_counts[uuid]}")
    else:
        uuid_counts[uuid] += 1
        new_uuids.append(f"{uuid}_doc{uuid_counts[uuid]}")

df_chunk_dev['uuid'] = new_uuids

print("Unique UUIDs created for df_chunk_dev.")
display(df_chunk_dev.head())

Unique UUIDs created for df_chunk_dev.

,uuid,messages,qrel,chunks
0,q7d7a32439929_doc0,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 0, '2': 0, '3': 0, '4': 1, '5': ...",Question: What share ownership guidelines are ...
1,qeb144d0e9991_doc0,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 0, '2': 0, '3': 0, '4': 0, '5': ...",Question: What exposure does Agilent Technolog...
2,qd79970afaa57_doc0,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 2, '2': 0, '3': 0, '4': 0, '5': ...",Question: How do sustainability or ESG conside...
3,q4f1cc6ea4ba6_doc0,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 0, '2': 0, '3': 0, '4': 0, '5': ...",Question: What sentiment trends are visible ar...
4,qc640e7d1c938_doc0,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 0, '2': 0, '3': 0, '4': 0, '5': ...",Question: What did Agilent Technologies’ execu...

In [ ]:
len(df_chunk_dev["uuid"].unique())

18855

## For chunks:
For annotating those relevance scores, we followed
TREC Eval: 0 (irrelevant), 1 (partially relevant), and 2 (directly relevant).

## Step 1: Differentiate between 2/1 and 0

In [ ]:
# Expected data layout (JSONL)

# train.jsonl: one object per (query, chunk, label)

# {"query_id":"Q1","query":"What are Apple’s 2023 gross margins?","chunk_id":"C1","chunk_text":"Item 7. Management’s Discussion... gross margin was 43% in 2023 ...","label":2}
# {"query_id":"Q1","query":"What are Apple’s 2023 gross margins?","chunk_id":"C2","chunk_text":"Risk Factors...","label":0}
# {"query_id":"Q2","query":"Did the company raise FY24 guidance?","chunk_id":"C9","chunk_text":"Earnings Call Q&A ... raised revenue guidance for FY24 ...","label":1}


# dev_corpus.jsonl: passage corpus (chunk_id → text)

# dev_queries.jsonl: eval queries (query_id → text)

# dev_qrels.jsonl: graded relevance (query_id, chunk_id, label ∈ {0,1,2})

# You can export these from your loader; labels 2/1 count as relevant for retrieval metrics.

In [ ]:
# add a

In [ ]:
from concurrent.futures import ProcessPoolExecutor, as_completed
import re

chunk_pattern = re.compile(
    r'\[Chunk Index (\d+)\]\s*([\s\S]*?)(?=\[Chunk Index|\bTask:|$)',
    # flags=re.MULTILINE
)

def process_row(args):
    idx, messages, uuid, qrel = args
    out = []
    try:
        content = messages[0]["content"]
    except Exception:
        return out

    question = None
    if "Question:" in content:
        part = content.split("Question:", 1)[1]
        question = part.splitlines()[0].strip() if part else None

    for m in chunk_pattern.finditer(content):
        orig_idx = int(m.group(1))
        chunk_text = m.group(2).strip()
        if "Task:" in chunk_text:
            chunk_text = chunk_text.split("Task:", 1)[0].strip()
        if not chunk_text:
            continue

        label = None
        try:
            label = qrel.get(str(orig_idx))
        except Exception:
            try:
                label = qrel.get(orig_idx)
            except Exception:
                label = None

        out.append({
            "query_id": uuid,
            "query": question,
            "chunk_id": uuid + "_chunk" + str(orig_idx),
            "chunk_text": chunk_text,
            "label": label
        })
    return out

# Build list of args
args_list = [(i, row.messages, row.uuid, row.qrel) for i, row in enumerate(df_chunk_dev.itertuples(index=False))]

results = []
with ProcessPoolExecutor() as ex:
    futures = {ex.submit(process_row, a): a for a in args_list}
    for fut in tqdm(as_completed(futures), total=len(futures)):
        results.extend(fut.result())

df_chunk_dev_sep_chunks = pd.DataFrame(results)

100%|██████████| 18855/18855 [01:41<00:00, 184.98it/s]

In [ ]:
df_chunk_dev_sep_chunks["query_id"][0]

'q7d7a32439929_doc0'

In [ ]:
df_chunk_dev_sep_chunks

,query_id,query,chunk_id,chunk_text,label
0,q7d7a32439929_doc0,What share ownership guidelines are defined fo...,q7d7a32439929_doc0_chunk0,# UNITED STATES\nSECURITIES AND EXCHANGE COMMI...,0
1,q7d7a32439929_doc0,What share ownership guidelines are defined fo...,q7d7a32439929_doc0_chunk1,"# 5301 Stevens Creek Boulevard Santa Clara, Ca...",0
2,q7d7a32439929_doc0,What share ownership guidelines are defined fo...,q7d7a32439929_doc0_chunk2,"# 5301 Stevens Creek Boulevard Santa Clara, Ca...",0
3,q7d7a32439929_doc0,What share ownership guidelines are defined fo...,q7d7a32439929_doc0_chunk3,# CAUTIONARY NOTE REGARDING FORWARD-LOOKING ST...,0
4,q7d7a32439929_doc0,What share ownership guidelines are defined fo...,q7d7a32439929_doc0_chunk4,# Director Nominees (cont.)\n\n## Corporate Go...,1
...,...,...,...,...,...
3193196,q4342a9af31f9_doc3,What guidance was offered regarding Zoetis Inc...,q4342a9af31f9_doc3_chunk262,SIGNATURES\n\nPursuant to the requirements of ...,0
3193197,q4342a9af31f9_doc3,What guidance was offered regarding Zoetis Inc...,q4342a9af31f9_doc3_chunk263,"####Zoetis Inc.##\nDated: February 13, 2024##B...",0
3193198,q4342a9af31f9_doc3,What guidance was offered regarding Zoetis Inc...,q4342a9af31f9_doc3_chunk264,"We, the undersigned directors and officers of ...",0
3193199,q4342a9af31f9_doc3,What guidance was offered regarding Zoetis Inc...,q4342a9af31f9_doc3_chunk265,Name####Title##Date\n/S/ KRISTIN C. PECK####Ch...,0
3193200,q4342a9af31f9_doc3,What guidance was offered regarding Zoetis Inc...,q4342a9af31f9_doc3_chunk266,99 |,0

In [ ]:
df_chunk_dev.head()

,uuid,messages,qrel,chunks
0,q7d7a32439929_doc0,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 0, '2': 0, '3': 0, '4': 1, '5': ...",Question: What share ownership guidelines are ...
1,qeb144d0e9991_doc0,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 0, '2': 0, '3': 0, '4': 0, '5': ...",Question: What exposure does Agilent Technolog...
2,qd79970afaa57_doc0,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 2, '2': 0, '3': 0, '4': 0, '5': ...",Question: How do sustainability or ESG conside...
3,q4f1cc6ea4ba6_doc0,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 0, '2': 0, '3': 0, '4': 0, '5': ...",Question: What sentiment trends are visible ar...
4,qc640e7d1c938_doc0,"[{'role': 'user', 'content': 'Identify the 10 ...","{'0': 0, '1': 0, '2': 0, '3': 0, '4': 0, '5': ...",Question: What did Agilent Technologies’ execu...

In [ ]:
df_doc_dev.head()

,uuid,messages,qrel,question
0,qe100cdf8e8f5,"[{'role': 'user', 'content': 'Rank the followi...","{'4': 1, '0': 0, '1': 0, '2': 0, '3': 0}",How has Agilent Technologies’ instrument relia...
1,q723817294fbe,"[{'role': 'user', 'content': 'Rank the followi...","{'4': 3, '0': 2, '1': 1, '3': 1, '2': 0}",How did analysts question the outlook for Agil...
2,qd79970afaa57,"[{'role': 'user', 'content': 'Rank the followi...","{'4': 3, '1': 2, '0': 1, '2': 1, '3': 0}",How do sustainability or ESG considerations in...
3,qeb144d0e9991,"[{'role': 'user', 'content': 'Rank the followi...","{'1': 3, '2': 2, '4': 1, '0': 0, '3': 0}","What exposure does Agilent Technologies, Inc. ..."
4,q4f1cc6ea4ba6,"[{'role': 'user', 'content': 'Rank the followi...","{'4': 3, '2': 2, '1': 1, '0': 0, '3': 0}",What sentiment trends are visible around Agile...

In [ ]:
df_doc_dev[df_doc_dev["uuid"] == "q4342a9af31f9"]

,uuid,messages,qrel,question
4980,q4342a9af31f9,"[{'role': 'user', 'content': 'Rank the followi...","{'4': 4, '3': 3, '1': 2, '2': 1, '0': 0}",What guidance was offered regarding Zoetis Inc...

In [ ]:
len(df_doc_dev)

4986

In [ ]:
len(df_chunk_dev)

18855

In [ ]:
len(df_chunk_dev["uuid"].unique())

18855

In [ ]:
df_chunk_dev_sep_chunks

,query_id,query,chunk_id,chunk_text,label
0,q7d7a32439929_doc0,What share ownership guidelines are defined fo...,q7d7a32439929_doc0_chunk0,# UNITED STATES\nSECURITIES AND EXCHANGE COMMI...,0
1,q7d7a32439929_doc0,What share ownership guidelines are defined fo...,q7d7a32439929_doc0_chunk1,"# 5301 Stevens Creek Boulevard Santa Clara, Ca...",0
2,q7d7a32439929_doc0,What share ownership guidelines are defined fo...,q7d7a32439929_doc0_chunk2,"# 5301 Stevens Creek Boulevard Santa Clara, Ca...",0
3,q7d7a32439929_doc0,What share ownership guidelines are defined fo...,q7d7a32439929_doc0_chunk3,# CAUTIONARY NOTE REGARDING FORWARD-LOOKING ST...,0
4,q7d7a32439929_doc0,What share ownership guidelines are defined fo...,q7d7a32439929_doc0_chunk4,# Director Nominees (cont.)\n\n## Corporate Go...,1
...,...,...,...,...,...
3193196,q4342a9af31f9_doc3,What guidance was offered regarding Zoetis Inc...,q4342a9af31f9_doc3_chunk262,SIGNATURES\n\nPursuant to the requirements of ...,0
3193197,q4342a9af31f9_doc3,What guidance was offered regarding Zoetis Inc...,q4342a9af31f9_doc3_chunk263,"####Zoetis Inc.##\nDated: February 13, 2024##B...",0
3193198,q4342a9af31f9_doc3,What guidance was offered regarding Zoetis Inc...,q4342a9af31f9_doc3_chunk264,"We, the undersigned directors and officers of ...",0
3193199,q4342a9af31f9_doc3,What guidance was offered regarding Zoetis Inc...,q4342a9af31f9_doc3_chunk265,Name####Title##Date\n/S/ KRISTIN C. PECK####Ch...,0
3193200,q4342a9af31f9_doc3,What guidance was offered regarding Zoetis Inc...,q4342a9af31f9_doc3_chunk266,99 |,0

In [ ]:
df_chunk_dev_sep_chunks.to_csv("df_chunk_dev_sep_chunks.csv", index=False)

In [ ]:
len(df_chunk_dev_sep_chunks)

3193201

In [ ]:
import argparse, json, random, math, os
from collections import defaultdict
from typing import Dict, List, Tuple

from torch.utils.data import Dataset, DataLoader
from sentence_transformers import SentenceTransformer, InputExample, losses, util, evaluation, models
from sentence_transformers.evaluation import InformationRetrievalEvaluator
import torch
from tqdm import tqdm

In [ ]:
df_chunk_dev_sep_chunks = pd.read_csv("df_chunk_dev_sep_chunks.csv")

In [ ]:
# utility

def load_jsonl(path):
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                yield json.loads(line)

def decide_prefixes(base_model: str):
    """
    Returns (q_prefix, p_prefix) recommended for the model family.
    BGE/E5 both benefit from 'query: ' / 'passage: ' style prefixes.
    """
    low = base_model.lower()
    if "bge" in low:
        return "query: ", "passage: "
    if "e5" in low:
        # E5 style also commonly uses 'query: ' / 'passage: '
        return "query: ", "passage: "
    # Fallback
    return "", ""

In [ ]:
# ----------------------------
# Dataset: one positive per (query_id), in-batch negatives between queries
# Optionally include a second view with a hard negative for multi-view InfoNCE
# ----------------------------

class FinAgentPairs(Dataset):
    def __init__(self, train_file, q_prefix: str, p_prefix: str, include_hard_neg: bool = True):
        """
        Builds (query, pos) pairs; keeps per-query 0-labeled chunks to sample as hard negatives.
        """
        self.q_prefix = q_prefix
        self.p_prefix = p_prefix
        self.include_hard_neg = include_hard_neg

        by_query_pos: Dict[str, List[Tuple[str, str]]] = defaultdict(list)   # qid -> list of (chunk_id, text) where label>=1
        by_query_neg: Dict[str, List[Tuple[str, str]]] = defaultdict(list)   # qid -> list of (chunk_id, text) where label==0
        self.query_text: Dict[str, str] = {}

        for i in range(len(df_chunk_dev_sep_chunks)):
            obj = df_chunk_dev_sep_chunks.iloc[i]
            qid = obj["query_id"]
            qtxt = obj["query"]
            cid = obj["chunk_id"]
            ctxt = obj["chunk_text"]
            label = int(obj["label"])
            self.query_text[qid] = qtxt
            if label >= 1:
                by_query_pos[qid].append((cid, ctxt))
            else:
                by_query_neg[qid].append((cid, ctxt))

        # Build one positive per (qid, sampled pos chunk) instance.
        self.samples = []
        for qid, pos_list in by_query_pos.items():
            if not pos_list:  # skip rare empty
                continue
            for cid, ctxt in pos_list:
                hard_negs = by_query_neg.get(qid, [])
                self.samples.append({
                    "query_id": qid,
                    "query": self.q_prefix + self.query_text[qid],
                    "pos_text": self.p_prefix + ctxt,
                    "hard_negs": [self.p_prefix + nctxt for _, nctxt in hard_negs] if hard_negs else []
                })

        random.shuffle(self.samples)

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        s = self.samples[idx]
        # Primary pair for MultipleNegativesRankingLoss:
        ex = InputExample(texts=[s["query"], s["pos_text"]])

        # Optionally add a multi-view form with a sampled hard negative.
        # Many folks simply rely on in-batch negatives; this adds a second view to strengthen within-query discrimination.
        if self.include_hard_neg and s["hard_negs"]:
            neg_text = random.choice(s["hard_negs"])
            # Tri-flow (anchor, pos, neg) for InfoNCE-like losses; MNRL ignores 3rd, but some variants accept it.
            # We'll return it in 'metadata' so a custom collate could use it if you switch to a triplet loss later.
            ex.metadata = {"hard_neg": neg_text}
        return ex

In [ ]:
import os, json, random, pickle
from collections import defaultdict
from typing import List, Dict, Any
from sentence_transformers import InputExample

class StreamingFinAgentPairs:
    """
    Memory-efficient dataset: store file offsets (ints) and query texts in memory,
    load chunk lines on demand by seeking into the jsonl file.
    """
    def __init__(self,
                 train_file: str,
                 q_prefix: str,
                 p_prefix: str,
                 include_hard_neg: bool = True,
                 index_path: str = None,
                 rebuild_index: bool = False,
                 seed: int = 42):
        """
        train_file: path to jsonl lines {'query_id','query','chunk_id','chunk_text','label'}
        index_path: optional path to save/load prebuilt index (.pkl)
        rebuild_index: force rebuild the index even if index_path exists
        """
        random.seed(seed)
        self.train_file = train_file
        self.q_prefix = q_prefix
        self.p_prefix = p_prefix
        self.include_hard_neg = include_hard_neg

        # Index structure we will keep in memory (compact)
        # queries[qid] = query_text
        # pos_index[qid] = list of offsets where label >=1 lines are located (file offsets)
        # neg_index[qid] = list of offsets where label == 0 lines are located
        self.queries: Dict[str, str] = {}
        self.pos_index: Dict[str, List[int]] = defaultdict(list)
        self.neg_index: Dict[str, List[int]] = defaultdict(list)
        self._ordered_pos_items = []  # list of tuples (qid, offset) to emulate one-sample-per-pos behavior

        # Try to load index if given
        if index_path and os.path.exists(index_path) and not rebuild_index:
            print(f"Loading index from {index_path} ...")

            # idx = pd.read_csv(index_path)
            with open(index_path, "rb") as fh:
                idx = pickle.load(fh)
            self.queries = idx["queries"]
            self.pos_index = idx["pos_index"]
            self.neg_index = idx["neg_index"]
            self._ordered_pos_items = idx.get("ordered_pos_items", [])
            print("Index loaded. Pos queries:", len(self.pos_index), "Neg queries:", len(self.neg_index))
        else:
            print("Building index from train file (one pass)...")
            self._build_index_and_ordered_list()
            if index_path:
                print(f"Saving index to {index_path} ...")
                # temp = pd.DataFrame({
                #     "queries": self.queries,
                #     "pos_index": self.pos_index,
                #     "neg_index": self.neg_index,
                #     "ordered_pos_items": self._ordered_pos_items
                # })
                # temp.to_csv(index_path)

                with open(index_path, "wb") as fh:
                    pickle.dump({
                        "queries": self.queries,
                        "pos_index": self.pos_index,
                        "neg_index": self.neg_index,
                        "ordered_pos_items": self._ordered_pos_items
                    }, fh)

    def _build_index_and_ordered_list(self):
        """
        Walk the jsonl file, keep offsets for each line and map offsets to pos/neg lists.
        """
        for i in range(len(df_chunk_dev_sep_chunks)):
          obj = df_chunk_dev_sep_chunks.iloc[i]
          qid = obj["query_id"]
          qtxt = obj["query"]
          cid = obj["chunk_id"]
          ctxt = obj["chunk_text"]
          label = int(obj["label"])
          # open in binary to get reliable tell() offsets
            # while True:
            #     offset = f.tell()
            #     line = f.readline()
            #     if not line:
            #         break
            #     try:
            #         obj = json.loads(line.decode("utf-8"))
            #     except Exception as e:
            #         # skip malformed line
            #         continue
          # qid = obj.get("query_id")
          # qtxt = obj.get("query", "")
          # cid = obj.get("chunk_id")
          # label = int(obj.get("label", 0))
          # store query text (last occurrence will match; queries are small)
          if qid not in self.queries:
              self.queries[qid] = qtxt
          # store offsets
          if label >= 1:
              self.pos_index[qid].append(i)
              # track ordered pos items for constructing dataset length & one-sample-per-pos behavior
              self._ordered_pos_items.append((qid, i))
          else:
              self.neg_index[qid].append(i)

        random.shuffle(self._ordered_pos_items)
        print("Indexed train file: queries =", len(self.queries),
              "total pos samples =", len(self._ordered_pos_items))

    def __len__(self):
        # we create one training sample per positive chunk occurrence (like before).
        return len(self._ordered_pos_items)

    def _read_line_at_offset(self, offset: int) -> dict:
        # read single json line at offset
        return df_chunk_dev_sep_chunks.iloc[offset]

    def __getitem__(self, idx: int) -> InputExample:
        """
        Returns InputExample(texts=[query_with_prefix, pos_with_prefix])
        and stores metadata.hard_neg if include_hard_neg is True and available.
        """
        qid, pos_offset = self._ordered_pos_items[idx]
        pos_obj = self._read_line_at_offset(pos_offset)
        pos_text = pos_obj["chunk_text"]

        q_text = self.queries[qid]

        # build example
        ex = InputExample(texts=[self.q_prefix + q_text, self.p_prefix + pos_text])

        # optionally sample a hard negative from same query (label 0)
        if self.include_hard_neg and self.neg_index.get(qid):
            neg_offset = random.choice(self.neg_index[qid])
            neg_obj = self._read_line_at_offset(neg_offset)
            ex.metadata = {"hard_neg": self.p_prefix + neg_obj["chunk_text"]}
        return ex

In [ ]:
# ----------------------------
# Dev evaluator (IR)
# ----------------------------

def build_ir_evaluator(dev_corpus_file, q_prefix, p_prefix):
    corpus = {}     # pid -> text
    queries = {}    # qid -> text
    relevant_docs = defaultdict(dict)  # qid -> {pid: relevance}

    for i in range(len(dev_corpus_file)):
      obj = dev_corpus_file.iloc[i]
      pid = obj["chunk_id"]
      corpus[pid] = p_prefix + obj["chunk_text"]

      qid = obj["query_id"]
      queries[qid] = q_prefix + obj["query"]

      label = int(obj["label"])
      if label >= 1:  # treat label≥1 as relevant for retrieval metrics; graded metrics computed internally
        relevant_docs[qid][pid] = label

    # for obj in load_jsonl(dev_corpus_file):
    #     pid = obj["chunk_id"]
    #     corpus[pid] = p_prefix + obj["chunk_text"]

    # for obj in load_jsonl(dev_queries_file):
    #     qid = obj["query_id"]
    #     queries[qid] = q_prefix + obj["query"]

    # for obj in load_jsonl(dev_qrels_file):
    #     qid = obj["query_id"]; pid = obj["chunk_id"]; label = int(obj["label"])
    #     if label >= 1:  # treat label≥1 as relevant for retrieval metrics; graded metrics computed internally
    #         relevant_docs[qid][pid] = label

    return InformationRetrievalEvaluator(
        queries=queries,
        corpus=corpus,
        relevant_docs=relevant_docs,
        name="finagentbench-dev",
        score_functions={"cos_sim": util.cos_sim},
        show_progress_bar=True
    )

In [ ]:
df_chunk_dev_sep_chunks.head()

,query_id,query,chunk_id,chunk_text,label
0,q7d7a32439929_doc0,What share ownership guidelines are defined fo...,q7d7a32439929_doc0_chunk0,# UNITED STATES\nSECURITIES AND EXCHANGE COMMI...,0
1,q7d7a32439929_doc0,What share ownership guidelines are defined fo...,q7d7a32439929_doc0_chunk1,"# 5301 Stevens Creek Boulevard Santa Clara, Ca...",0
2,q7d7a32439929_doc0,What share ownership guidelines are defined fo...,q7d7a32439929_doc0_chunk2,"# 5301 Stevens Creek Boulevard Santa Clara, Ca...",0
3,q7d7a32439929_doc0,What share ownership guidelines are defined fo...,q7d7a32439929_doc0_chunk3,# CAUTIONARY NOTE REGARDING FORWARD-LOOKING ST...,0
4,q7d7a32439929_doc0,What share ownership guidelines are defined fo...,q7d7a32439929_doc0_chunk4,# Director Nominees (cont.)\n\n## Corporate Go...,1

In [ ]:
train_file = df_chunk_dev_sep_chunks
dev_corpus = df_chunk_dev_sep_chunks
# dev_corpus = df_chunk_dev_sep_chunks["chunk_text"]
# dev_queries = df_chunk_dev_sep_chunks["query_id"]
# dev_qrels = df_chunk_dev_sep_chunks["qrel"]
base_model = "BAAI/bge-large-en-v1.5"
output_dir = "output"
batch_size = 64
epochs = 2
lr = 2e-5
max_seq_length = 512
warmup_ratio = 0.1
fp16 = True
seed = 42
include_hard_neg = "True"

random.seed(seed)
torch.manual_seed(seed)

os.makedirs(output_dir, exist_ok=True)

In [ ]:
q_prefix, p_prefix = decide_prefixes(base_model)

print(f"Loading base model: {base_model}")
model = SentenceTransformer(base_model)
model.max_seq_length = max_seq_length

Loading base model: BAAI/bge-large-en-v1.5

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/779 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

In [ ]:
# Training data

# train_ds = FinAgentPairs(train_file, q_prefix, p_prefix, include_hard_neg=include_hard_neg)

# IMPORTANT: ensure one pair per unique query per batch to maximize in-batch negatives.
# We do that by sorting by query_id and using a sampler that picks distinct queries.
# Simpler practical trick: shuffle samples globally and set batch_size so that probability of duplicate qids within a batch is low.
# For strictness you can implement a custom sampler; for most FinAgentBench sizes, BS=64 with shuffle=True works well.

# train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, drop_last=True)

In [ ]:
train_ds = StreamingFinAgentPairs(
    train_file=train_file,
    q_prefix=q_prefix,
    p_prefix=p_prefix,
    include_hard_neg=True,
    index_path="train_index.pkl",   # optional cache
    rebuild_index=False
)

train_loader = DataLoader(train_ds, batch_size=32, shuffle=True, num_workers=4, pin_memory=False)

Building index from train file (one pass)...
Indexed train file: queries = 18855 total pos samples = 164066
Saving index to train_index.pkl ...

In [ ]:
# Loss: MultipleNegativesRankingLoss (InfoNCE for bi-encoders)
train_loss = losses.MultipleNegativesRankingLoss(model)

In [ ]:
# Dev evaluator
evaluator = build_ir_evaluator(dev_corpus, q_prefix, p_prefix)

warmup_steps = math.ceil(len(train_loader) * epochs * warmup_ratio)

In [ ]:
# Train
os.environ["WANDB_DISABLED"] = "true"

model.fit(
    train_objectives=[(train_loader, train_loss)],
    epochs=epochs,
    optimizer_params={"lr": lr},
    warmup_steps=warmup_steps,
    output_path=output_dir,
    save_best_model=True,
    evaluator=evaluator,
    evaluation_steps=max(100, len(train_loader)//5),
    use_amp=fp16,
    show_progress_bar=True,
)

print("Finished training. Saving final model...")
model.save(output_dir)

# Final evaluation
print("Running final evaluation on dev …")
model = SentenceTransformer(output_dir)
evaluator(model, output_path=output_dir)

print("Done. Model at:", output_dir)

## DeepSeek

In [ ]:
client = AsyncOpenAI(api_key=DEEPSEEK_API_KEY, base_url="https://api.deepseek.com")

In [ ]:
async def deepseek_model_chunks(system_prompt, user_prompt):
    """Generates Question-Thought-Answer triplets from the given text using OpenAI."""
    try:
        response = await client.chat.completions.create(
            model="deepseek-chat",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            # response_format={"type": "json_object"}
        )

        # print(response)

        # Attempt to parse the response as JSON
        # try:
        #     rankings = json.loads(response.choices[0].message.content)
        #     return rankings
        # except json.JSONDecodeError as e:
        #     print(f"Error decoding JSON from model response: {e}")
        #     print("Raw response text:", response.choices[0].message.content)
        #     return []

        return response

    except Exception as e:
        print(f"An error occurred during ranking generation: {e}")
        return []

In [ ]:
deepseek_prompts = []

system_prompt_chunk = """You are a helpful assistant that provides financial document chunk rankings based on which chunk is most likely to contain the information relevant to the question. Do not add any thinking, reasoning or other texts."""

for index, row in df_chunk_eval.iterrows():
    eval_question_chunk = row['chunks']

    prompt = f"""Evaluate the relevance ranking of the chunks for the following question based on how relevant the content in chunk is for answering the question.\n\n{eval_question_chunk}\n\n"""

    prompt += """Your Task:\nRank the chunks on one of the three numbers: 0 (chunk is irrelevant in answering the question asked), 1 (chunk is partially relevant in answering the question asked), and 2 (chunk is directly relevant in answering the question asked). Return the result rankings in a JSON format in the form: {'0':1, '1':0..} where keys are the chunk numbers and values are the ranks assigned.\nAnswer Ranking:"""

    deepseek_prompts.append(prompt)

df_chunk_eval['deepseek_prompts'] = deepseek_prompts

print("DeepSeek prompts generated and added to df_doc_eval.")
display(df_chunk_eval.head())

DeepSeek prompts generated and added to df_doc_eval.

,_id,messages,chunks,deepseek_prompts
0,chunk_q613509,"[{'role': 'user', 'content': 'Identify the 10 ...",Question: What guidance was offered on Ball Co...,Evaluate the relevance ranking of the chunks f...
1,chunk_q83d560,"[{'role': 'user', 'content': 'Identify the 10 ...",Question: How has the ratio of BlackRock’s rec...,Evaluate the relevance ranking of the chunks f...
2,chunk_qc06926,"[{'role': 'user', 'content': 'Identify the 10 ...",Question: How has Caterpillar Inc.’s construct...,Evaluate the relevance ranking of the chunks f...
3,chunk_qaae0f2,"[{'role': 'user', 'content': 'Identify the 10 ...",Question: How do global economic or geopolitic...,Evaluate the relevance ranking of the chunks f...
4,chunk_q059068,"[{'role': 'user', 'content': 'Identify the 10 ...",Question: What did Chubb Limited’s leadership ...,Evaluate the relevance ranking of the chunks f...

In [ ]:
df_chunk_eval["deepseek_prompts"][0]

"Evaluate the relevance ranking of the chunks for the following question based on how relevant the content in chunk is for answering the question.\n\nQuestion: What guidance was offered on Ball Corporation’s aluminum can production capacity targets?\nText chunks:\n[Chunk Index 0] PART I. FINANCIAL INFORMATION\n\nItem 1. FINANCIAL STATEMENTS\n\nBALL CORPORATION\n\nUNAUDITED CONDENSED CONSOLIDATED STATEMENTS OF EARNINGS\n[Chunk Index 1] ######Three Months Ended September 30,##########Nine Months Ended September 30,####\n($ in millions, except per share amounts)####2023######2022####2023######2022\nNet sales##$##3,571####$##3,951##$##10,626####$##11,801\nCosts and expenses####################\nCost of sales (excluding depreciation and amortization)####(2,894)######(3,275)####(8,655)######(9,736)\nDepreciation and amortization####(173)######(157)####(509)######(510)\nSelling, general and administrative####(132)######(159)####(428)######(506)\nBusiness consolidation and other activities####(47)######163####(61)######(23)\n####(3,246)######(3,428)####(9,653)######(10,775)\nEarnings before interest and taxes####325######523####973######1,026\nInterest expense####(122)######(79)####(350)######(216)\nDebt refinancing and other costs####—######—####—######(2)\nTotal interest expense####(122)######(79)####(350)######(218)\nEarnings before taxes####203######444####623######808\nTax (provision) benefit####(2)######(38)####(79)######(139)\nEquity in results of affiliates, net of tax####3######(12)####13######7\nNet earnings####204######394####557######676\nNet earnings attributable to noncontrolling interests####1######2####4######12\nNet earnings attributable to Ball Corporation##$##203####$##392##$##553####$##664\nEarnings per share:####################\nBasic##$##0.64####$##1.25##$##1.76####$##2.09\nDiluted##$##0.64####$##1.24##$##1.74####$##2.07\nWeighted average shares outstanding: (000s)####################\nBasic####314,983######314,054####314,596######317,296\nDiluted####317,296######317,061####316,938######321,222\n[Chunk Index 2] See accompanying notes to the unaudited condensed consolidated financial statements.\n\n1\n[Chunk Index 3] BALL CORPORATION\n\nUNAUDITED CONDENSED CONSOLIDATED STATEMENTS OF COMPREHENSIVE EARNINGS (LOSS)\n[Chunk Index 4] ######Three Months Ended September 30,##########Nine Months Ended September 30,####\n($ in millions)####2023######2022####2023######2022\nNet earnings##$##204####$##394##$##557####$##676\nOther comprehensive earnings (loss):####################\nCurrency translation adjustment####(40)######(203)####18######51\nPension and other postretirement benefits####(1)######(1)####8######1\nDerivatives designated as hedges####(30)######(129)####14######(148)\nTotal other comprehensive earnings (loss)####(71)######(333)####40######(96)\nIncome tax (provision) benefit####11######31####(3)######30\nTotal other comprehensive earnings (loss), net of tax####(60)######(302)####37######(66)\nTotal comprehensive earnings####144######92####594######610\nComprehensive earnings attributable to noncontrolling interests####1######2####4######12\nComprehensive earnings attributable to Ball Corporation##$##143####$##90##$##590####$##598\n[Chunk Index 5] See accompanying notes to the unaudited condensed consolidated financial statements.\n\n2\n[Chunk Index 6] BALL CORPORATION\n\nUNAUDITED CONDENSED CONSOLIDATED BALANCE SHEETS\n[Chunk Index 7] ####September 30,####December 31,\n($ in millions)####2023####2022\nAssets########\nCurrent assets########\nCash and cash equivalents##$##1,335##$##548\nReceivables, net####2,059####2,594\nInventories, net####1,688####2,179\nOther current assets####326####168\nTotal current assets####5,408####5,489\nNoncurrent assets########\nProperty, plant and equipment, net####7,264####7,053\nGoodwill####4,222####4,235\nIntangible assets, net####1,315####1,417\nOther assets####1,723####1,715\nTotal assets##$##19,932##$##19,909\nLiabilities and Equity########\nCurrent liabilities########\nShort-term debt and current portion of long-term debt##$##2,108##$##1,408\nAccounts payable####3,294####4,383\nAccrued employee costs####310####236\nOther current liabilities####1,003####981\nTotal current liabilities####6,715####7,008\nNoncurrent liabilities########\nLong-term debt####7,483####7,540\nEmployee benefit obligations####813####847\nDeferred taxes####445####540\nOther liabilities####468####447\nTotal liabilities####15,924####16,382\nEquity########\nCommon stock (682,896,369 shares issued - 2023; 682,144,408 shares issued - 2022)####1,304####1,260\nRetained earnings####7,673####7,309\nAccumulated other comprehensive earnings (loss)####(642)####(679)\nTreasury stock, at cost (367,662,311 shares - 2023; 368,036,369 shares - 2022)####(4,397)####(4,429)\nTotal Ball Corporation shareholders' equity####3,938####3,461\nNoncontrolling interests####70####66\nTotal equity####4,008####3,527\nTotal liabilities and equity##$##19,932##$##19,909\n[Chunk Index 8] See accompanying notes to the unaudited condensed consolidated financial statements.\n\n3\n[Chunk Index 9] BALL CORPORATION\n\nUNAUDITED CONDENSED CONSOLIDATED STATEMENTS OF CASH FLOWS\n[Chunk Index 10] ######Nine Months Ended September 30,####\n($ in millions)####2023######2022\nCash Flows from Operating Activities##########\nNet earnings##$##557####$##676\nAdjustments to reconcile net earnings to cash provided by (used in) operating activities:##########\nDepreciation and amortization####509######510\nBusiness consolidation and other activities####61######23\nDeferred tax provision (benefit)####(87)######(23)\nPension contributions####(13)######(113)\nOther, net####71######(165)\nChanges in working capital components, net of dispositions####29######(1,132)\nCash provided by (used in) operating activities####1,127######(224)\nCash Flows from Investing Activities##########\nCapital expenditures####(830)######(1,262)\nBusiness dispositions, net of cash sold####—######748\nOther, net####4######62\nCash provided by (used in) investing activities####(826)######(452)\nCash Flows from Financing Activities##########\nLong-term borrowings####1,700######3,401\nRepayments of long-term borrowings####(913)######(2,446)\nNet change in short-term borrowings####(135)######463\nAcquisitions of treasury stock####(3)######(617)\nCommon stock dividends####(189)######(191)\nOther, net####30######13\nCash provided by (used in) financing activities####490######623\nEffect of exchange rate changes on cash####—######(30)\nChange in cash, cash equivalents and restricted cash####791######(83)\nCash, cash equivalents and restricted cash - beginning of period####558######579\nCash, cash equivalents and restricted cash - end of period##$##1,349####$##496\n[Chunk Index 11] See accompanying notes to the unaudited condensed consolidated financial statements.\n\n4\n[Chunk Index 12] 1. Basis of Presentation\n\nThe accompanying unaudited condensed consolidated financial statements (consolidated financial statements) include the accounts of Ball Corporation and its controlled affiliates, including its consolidated variable interest entities (collectively Ball, the company, we or our), and have been prepared by the company. Certain information and footnote disclosures, including critical and significant accounting policies normally included in consolidated financial statements prepared in accordance with generally accepted accounting principles, have been condensed or omitted for this quarterly presentation.\n\nResults of operations for the periods shown are not necessarily indicative of results for the year, particularly in view of the seasonality in the packaging segments and the variability of contract sales in the company’s aerospace segment. These consolidated financial statements and accompanying notes should be read in conjunction with the consolidated financial statements and the notes thereto included in the company’s 2022 Annual Report on Form 10-K filed on February 21, 2023, pursuant to the Securities Exchange Act of 1934 for the fiscal year ended December 31, 2022 (annual report).\n\nThe preparation of consolidated financial statements in conformity with accounting principles generally accepted in the United States of America (U.S. GAAP) requires Ball’s management to make estimates and assumptions that affect the reported amounts of assets and liabilities and disclosure of contingent liabilities at the date of the consolidated financial statements and reported amounts of revenues and expenses during the reporting periods. These estimates are based on historical experience and various assumptions believed to be reasonable under the circumstances. Ball’s management evaluates these estimates on an ongoing basis and adjusts or revises the estimates as circumstances change. As future events and their impacts cannot be determined with precision, actual results may differ from these estimates. In the opinion of management, the consolidated financial statements reflect all adjustments that are of a normal recurring nature and are necessary to fairly state the results of the periods presented.\n\nCertain prior year amounts have been reclassified in order to conform to the current year presentation.\n\nRisks and Uncertainties\n\nGlobal Economic Environment\n\nRecent data has indicated continued high inflation in the regions where we operate. Current and future inflationary effects may continue to be impacted by, among other things, supply chain disruptions, governmental stimulus or fiscal policies, changes in interest rates, and changing demand for certain goods and services as recovery from the COVID-19 pandemic continues. We cannot predict with any certainty the impact that rising interest rates, a global or any regional recession, or higher inflation may have on our customers or suppliers. Additionally, we are unable to predict the potential effects that any future pandemic, or the continuation or escalation of global conflicts, including the conflict between Russia and Ukraine and the rising instability in the Middle East, and related sanctions or market disruptions, may have on our business. It remains uncertain how long any of these conditions may last or how severe any of them may become.\n\nBall management has reviewed the estimates used in preparing the company’s consolidated financial statements and the following have a reasonably possible likelihood of being affected, to a material extent, by the direct and indirect impacts of the current global economic environment in the near term.\n\n● Estimates regarding the future financial performance of the business used in the impairment tests for goodwill, long-lived assets, equity method investments, recoverability of deferred tax assets and estimates regarding cash needs and associated indefinite reinvestment assertions;\n\n● Estimates of recoverability for customer receivables;\n\n● Estimates of net realizable value for inventory; and\n\n● Estimates regarding the likelihood of forecasted transactions associated with hedge accounting positions at September 30, 2023, which could impact the company’s ability to satisfy hedge accounting requirements and result in the recognition of income and/or expenses.\n\n5\n[Chunk Index 13] In addition to the above potential impacts on the estimates used in preparing the consolidated financial statements, the current global economic environment has the potential to increase Ball’s vulnerabilities to near-term severe impacts related to certain concentrations in its business. In line with other companies in the packaging and aerospace industries, Ball makes the majority of its sales and significant purchases to or from a relatively small number of global, or large regional, customers and suppliers. Furthermore, Ball makes the majority of its sales from a small number of product lines. The potential of the current global economic environment to affect a significant customer or supplier, or to affect demand for certain products to a significant degree, heightens the vulnerability of Ball to these concentrations.\n\n2. Accounting Pronouncements\n\nRecently Adopted Accounting Standards\n\nSupplier Finance Programs\n\nIn 2022, new guidance was issued by the FASB with the goal of enhancing transparency around supplier finance programs. On January 1, 2023, Ball adopted all required disclosures effective for 2023, on a retrospective basis. The company will adopt the rollforward disclosure requirements, on a prospective basis, when they become effective in 2024.\n\nThe company has several regional supplier finance programs, all of which have substantially similar characteristics, with various financial institutions that act as the paying agent for certain payables of the company. The company establishes these programs through agreements with the financial institutions to enable more efficient payment processing to our suppliers while also providing our suppliers a potential source of liquidity to the extent they enter into a factoring agreement with the financial institutions. Our suppliers’ participation in the programs is voluntary, and the company is not involved in negotiations of the suppliers’ arrangements with the financial institutions to sell their receivables, and our rights and obligations to our suppliers are not impacted by our suppliers’ decisions to sell amounts under these programs. Under these supplier finance programs, the company pays the financial institutions the stated amount of confirmed invoices from its participating suppliers on the original maturity dates of the invoices, which vary based on the negotiated terms with each supplier. All payment terms are short-term in nature and are not dependent on whether the suppliers participate in the supplier finance programs or if the suppliers elect to receive early payment from the financial institutions. Our supplier finance programs do not include any of the following: guarantees to the financial institutions, assets pledged as securities or interest accruing on the obligation prior to the due date.\n\nBased on the review of the facts and circumstances of our supplier finance programs, including but not limited to those noted above, the company has concluded that the characteristics of the obligations due under our supplier finance programs have not changed and remain those of standard accounts payables, rather than indicative of debt.\n\nThe amount of obligations outstanding that the company confirmed as valid to the financial institutions under the company's programs was $512 million and $930 million at September 30, 2023 and December 31, 2022, respectively. These amounts are classified within accounts payable on the unaudited condensed consolidated balance sheets, and the associated payments are reflected in the cash flows from operating activities section of the unaudited condensed consolidated statements of cash flows.\n\n3. Business Segment Information\n\nBall’s operations are organized and reviewed by management along its product lines and geographical areas and presented in the four reportable segments outlined below.\n\nBeverage packaging, North and Central America: Consists of operations in the U.S., Canada and Mexico that manufacture and sell aluminum beverage containers throughout those countries.\n\nBeverage packaging, EMEA: Consists of operations in numerous countries throughout Europe, as well as Egypt and Turkey, that manufacture and sell aluminum beverage containers throughout those countries. Ball sold its former operations located in Russia during the third quarter of 2022. See Note 4 for further details. Ball’s operations and results of its former Russian aluminum beverage packaging business are included in the results of the beverage packaging, EMEA, business through the date of the disposal in the third quarter of 2022.\n\n6\n[Chunk Index 14] Beverage packaging, South America: Consists of operations in Brazil, Argentina, Paraguay and Chile that manufacture and sell aluminum beverage containers throughout most of South America.\n\nAerospace: Consists of operations that manufacture and sell aerospace and other related products and provide services used in the defense, civil space and commercial space industries. In the third quarter of 2023, Ball entered into a Stock Purchase Agreement with BAE Systems, Inc., to sell all of the outstanding equity interests in Ball’s aerospace business to BAE. See Note 4 for further details.\n\nAs presented in the table below, Other consists of a non-reportable operating segment (beverage packaging, other) that manufactures and sells aluminum beverage containers in India, Saudi Arabia and throughout the Asia Pacific region; a non-reportable operating segment that manufactures and sells extruded aluminum aerosol containers and recloseable aluminum bottles across multiple consumer categories as well as aluminum slugs (aerosol packaging) throughout North America, South America, Europe, and Asia; a non-reportable operating segment that manufactures and sells aluminum cups (aluminum cups); undistributed corporate expenses; and intercompany eliminations and other business activities.\n\nThe accounting policies of the segments are the same as those used in the consolidated financial statements, as discussed in Note 1. The company also has investments in operations in Guatemala, Panama, the U.S. and Vietnam that are accounted for under the equity method of accounting and, accordingly, those results are not included in segment sales or earnings. In the first quarter of 2022, Ball sold its remaining equity method investment in Ball Metalpack. Refer to Note 4 for additional details.\n\n7\n[Chunk Index 15] Summary of Business by Segment\n[Chunk Index 16] ######Three Months Ended September 30,##########Nine Months Ended September 30,####\n($ in millions)####2023######2022####2023######2022\nNet sales####################\nBeverage packaging, North and Central America##$##1,541####$##1,800##$##4,582####$##5,184\nBeverage packaging, EMEA####902######1,031####2,656######3,106\nBeverage packaging, South America####489######466####1,344######1,494\nAerospace####460######477####1,467######1,471\nReportable segment sales####3,392######3,774####10,049######11,255\nOther####179######177####577######546\nNet sales##$##3,571####$##3,951##$##10,626####$##11,801\nComparable operating earnings####################\nBeverage packaging, North and Central America##$##196####$##205##$##554####$##543\nBeverage packaging, EMEA####103######82####274######311\nBeverage packaging, South America####61######67####141######197\nAerospace####46######47####160######126\nReportable segment comparable operating earnings####406######401####1,129######1,177\nReconciling items####################\nOther (a)####—######(8)####7######(26)\nBusiness consolidation and other activities####(47)######163####(61)######(23)\nAmortization of acquired intangibles####(34)######(33)####(102)######(102)\nEarnings before interest and taxes####325######523####973######1,026\nInterest expense####(122)######(79)####(350)######(216)\nDebt refinancing and other costs####—######—####—######(2)\nTotal interest expense####(122)######(79)####(350)######(218)\nEarnings before taxes##$##203####$##444##$##623####$##808\n[Chunk Index 17] (a) Includes undistributed corporate expenses, net, of $18 million and $25 million for the three months ended September 30, 2023 and 2022, respectively, and $60 million and $73 million for the nine months ended September 30, 2023 and 2022, respectively.\n\nThe company does not disclose total assets by segment as such information is not provided to the chief operating decision maker.\n\n4. Acquisitions and Dispositions\n\nAerospace\n\nIn the third quarter of 2023, Ball entered into a Stock Purchase Agreement (Agreement) with BAE Systems, Inc. (BAE) and, for the limited purposes set forth therein, BAE Systems plc, to sell all of the outstanding equity interests in Ball’s aerospace business to BAE for a purchase price o

In [ ]:
df_chunk_eval["messages"][0][0]['content']

"Identify the 10 most relevant text chunks for answering this question, then rank them in order of relevance (best first).\nQuestion: What guidance was offered on Ball Corporation’s aluminum can production capacity targets?\nText chunks:\n[Chunk Index 0] PART I. FINANCIAL INFORMATION\n\nItem 1. FINANCIAL STATEMENTS\n\nBALL CORPORATION\n\nUNAUDITED CONDENSED CONSOLIDATED STATEMENTS OF EARNINGS\n[Chunk Index 1] ######Three Months Ended September 30,##########Nine Months Ended September 30,####\n($ in millions, except per share amounts)####2023######2022####2023######2022\nNet sales##$##3,571####$##3,951##$##10,626####$##11,801\nCosts and expenses####################\nCost of sales (excluding depreciation and amortization)####(2,894)######(3,275)####(8,655)######(9,736)\nDepreciation and amortization####(173)######(157)####(509)######(510)\nSelling, general and administrative####(132)######(159)####(428)######(506)\nBusiness consolidation and other activities####(47)######163####(61)######(23)\n####(3,246)######(3,428)####(9,653)######(10,775)\nEarnings before interest and taxes####325######523####973######1,026\nInterest expense####(122)######(79)####(350)######(216)\nDebt refinancing and other costs####—######—####—######(2)\nTotal interest expense####(122)######(79)####(350)######(218)\nEarnings before taxes####203######444####623######808\nTax (provision) benefit####(2)######(38)####(79)######(139)\nEquity in results of affiliates, net of tax####3######(12)####13######7\nNet earnings####204######394####557######676\nNet earnings attributable to noncontrolling interests####1######2####4######12\nNet earnings attributable to Ball Corporation##$##203####$##392##$##553####$##664\nEarnings per share:####################\nBasic##$##0.64####$##1.25##$##1.76####$##2.09\nDiluted##$##0.64####$##1.24##$##1.74####$##2.07\nWeighted average shares outstanding: (000s)####################\nBasic####314,983######314,054####314,596######317,296\nDiluted####317,296######317,061####316,938######321,222\n[Chunk Index 2] See accompanying notes to the unaudited condensed consolidated financial statements.\n\n1\n[Chunk Index 3] BALL CORPORATION\n\nUNAUDITED CONDENSED CONSOLIDATED STATEMENTS OF COMPREHENSIVE EARNINGS (LOSS)\n[Chunk Index 4] ######Three Months Ended September 30,##########Nine Months Ended September 30,####\n($ in millions)####2023######2022####2023######2022\nNet earnings##$##204####$##394##$##557####$##676\nOther comprehensive earnings (loss):####################\nCurrency translation adjustment####(40)######(203)####18######51\nPension and other postretirement benefits####(1)######(1)####8######1\nDerivatives designated as hedges####(30)######(129)####14######(148)\nTotal other comprehensive earnings (loss)####(71)######(333)####40######(96)\nIncome tax (provision) benefit####11######31####(3)######30\nTotal other comprehensive earnings (loss), net of tax####(60)######(302)####37######(66)\nTotal comprehensive earnings####144######92####594######610\nComprehensive earnings attributable to noncontrolling interests####1######2####4######12\nComprehensive earnings attributable to Ball Corporation##$##143####$##90##$##590####$##598\n[Chunk Index 5] See accompanying notes to the unaudited condensed consolidated financial statements.\n\n2\n[Chunk Index 6] BALL CORPORATION\n\nUNAUDITED CONDENSED CONSOLIDATED BALANCE SHEETS\n[Chunk Index 7] ####September 30,####December 31,\n($ in millions)####2023####2022\nAssets########\nCurrent assets########\nCash and cash equivalents##$##1,335##$##548\nReceivables, net####2,059####2,594\nInventories, net####1,688####2,179\nOther current assets####326####168\nTotal current assets####5,408####5,489\nNoncurrent assets########\nProperty, plant and equipment, net####7,264####7,053\nGoodwill####4,222####4,235\nIntangible assets, net####1,315####1,417\nOther assets####1,723####1,715\nTotal assets##$##19,932##$##19,909\nLiabilities and Equity########\nCurrent liabilities########\nShort-term debt and current portion of long-term debt##$##2,108##$##1,408\nAccounts payable####3,294####4,383\nAccrued employee costs####310####236\nOther current liabilities####1,003####981\nTotal current liabilities####6,715####7,008\nNoncurrent liabilities########\nLong-term debt####7,483####7,540\nEmployee benefit obligations####813####847\nDeferred taxes####445####540\nOther liabilities####468####447\nTotal liabilities####15,924####16,382\nEquity########\nCommon stock (682,896,369 shares issued - 2023; 682,144,408 shares issued - 2022)####1,304####1,260\nRetained earnings####7,673####7,309\nAccumulated other comprehensive earnings (loss)####(642)####(679)\nTreasury stock, at cost (367,662,311 shares - 2023; 368,036,369 shares - 2022)####(4,397)####(4,429)\nTotal Ball Corporation shareholders' equity####3,938####3,461\nNoncontrolling interests####70####66\nTotal equity####4,008####3,527\nTotal liabilities and equity##$##19,932##$##19,909\n[Chunk Index 8] See accompanying notes to the unaudited condensed consolidated financial statements.\n\n3\n[Chunk Index 9] BALL CORPORATION\n\nUNAUDITED CONDENSED CONSOLIDATED STATEMENTS OF CASH FLOWS\n[Chunk Index 10] ######Nine Months Ended September 30,####\n($ in millions)####2023######2022\nCash Flows from Operating Activities##########\nNet earnings##$##557####$##676\nAdjustments to reconcile net earnings to cash provided by (used in) operating activities:##########\nDepreciation and amortization####509######510\nBusiness consolidation and other activities####61######23\nDeferred tax provision (benefit)####(87)######(23)\nPension contributions####(13)######(113)\nOther, net####71######(165)\nChanges in working capital components, net of dispositions####29######(1,132)\nCash provided by (used in) operating activities####1,127######(224)\nCash Flows from Investing Activities##########\nCapital expenditures####(830)######(1,262)\nBusiness dispositions, net of cash sold####—######748\nOther, net####4######62\nCash provided by (used in) investing activities####(826)######(452)\nCash Flows from Financing Activities##########\nLong-term borrowings####1,700######3,401\nRepayments of long-term borrowings####(913)######(2,446)\nNet change in short-term borrowings####(135)######463\nAcquisitions of treasury stock####(3)######(617)\nCommon stock dividends####(189)######(191)\nOther, net####30######13\nCash provided by (used in) financing activities####490######623\nEffect of exchange rate changes on cash####—######(30)\nChange in cash, cash equivalents and restricted cash####791######(83)\nCash, cash equivalents and restricted cash - beginning of period####558######579\nCash, cash equivalents and restricted cash - end of period##$##1,349####$##496\n[Chunk Index 11] See accompanying notes to the unaudited condensed consolidated financial statements.\n\n4\n[Chunk Index 12] 1. Basis of Presentation\n\nThe accompanying unaudited condensed consolidated financial statements (consolidated financial statements) include the accounts of Ball Corporation and its controlled affiliates, including its consolidated variable interest entities (collectively Ball, the company, we or our), and have been prepared by the company. Certain information and footnote disclosures, including critical and significant accounting policies normally included in consolidated financial statements prepared in accordance with generally accepted accounting principles, have been condensed or omitted for this quarterly presentation.\n\nResults of operations for the periods shown are not necessarily indicative of results for the year, particularly in view of the seasonality in the packaging segments and the variability of contract sales in the company’s aerospace segment. These consolidated financial statements and accompanying notes should be read in conjunction with the consolidated financial statements and the notes thereto included in the company’s 2022 Annual Report on Form 10-K filed on February 21, 2023, pursuant to the Securities Exchange Act of 1934 for the fiscal year ended December 31, 2022 (annual report).\n\nThe preparation of consolidated financial statements in conformity with accounting principles generally accepted in the United States of America (U.S. GAAP) requires Ball’s management to make estimates and assumptions that affect the reported amounts of assets and liabilities and disclosure of contingent liabilities at the date of the consolidated financial statements and reported amounts of revenues and expenses during the reporting periods. These estimates are based on historical experience and various assumptions believed to be reasonable under the circumstances. Ball’s management evaluates these estimates on an ongoing basis and adjusts or revises the estimates as circumstances change. As future events and their impacts cannot be determined with precision, actual results may differ from these estimates. In the opinion of management, the consolidated financial statements reflect all adjustments that are of a normal recurring nature and are necessary to fairly state the results of the periods presented.\n\nCertain prior year amounts have been reclassified in order to conform to the current year presentation.\n\nRisks and Uncertainties\n\nGlobal Economic Environment\n\nRecent data has indicated continued high inflation in the regions where we operate. Current and future inflationary effects may continue to be impacted by, among other things, supply chain disruptions, governmental stimulus or fiscal policies, changes in interest rates, and changing demand for certain goods and services as recovery from the COVID-19 pandemic continues. We cannot predict with any certainty the impact that rising interest rates, a global or any regional recession, or higher inflation may have on our customers or suppliers. Additionally, we are unable to predict the potential effects that any future pandemic, or the continuation or escalation of global conflicts, including the conflict between Russia and Ukraine and the rising instability in the Middle East, and related sanctions or market disruptions, may have on our business. It remains uncertain how long any of these conditions may last or how severe any of them may become.\n\nBall management has reviewed the estimates used in preparing the company’s consolidated financial statements and the following have a reasonably possible likelihood of being affected, to a material extent, by the direct and indirect impacts of the current global economic environment in the near term.\n\n● Estimates regarding the future financial performance of the business used in the impairment tests for goodwill, long-lived assets, equity method investments, recoverability of deferred tax assets and estimates regarding cash needs and associated indefinite reinvestment assertions;\n\n● Estimates of recoverability for customer receivables;\n\n● Estimates of net realizable value for inventory; and\n\n● Estimates regarding the likelihood of forecasted transactions associated with hedge accounting positions at September 30, 2023, which could impact the company’s ability to satisfy hedge accounting requirements and result in the recognition of income and/or expenses.\n\n5\n[Chunk Index 13] In addition to the above potential impacts on the estimates used in preparing the consolidated financial statements, the current global economic environment has the potential to increase Ball’s vulnerabilities to near-term severe impacts related to certain concentrations in its business. In line with other companies in the packaging and aerospace industries, Ball makes the majority of its sales and significant purchases to or from a relatively small number of global, or large regional, customers and suppliers. Furthermore, Ball makes the majority of its sales from a small number of product lines. The potential of the current global economic environment to affect a significant customer or supplier, or to affect demand for certain products to a significant degree, heightens the vulnerability of Ball to these concentrations.\n\n2. Accounting Pronouncements\n\nRecently Adopted Accounting Standards\n\nSupplier Finance Programs\n\nIn 2022, new guidance was issued by the FASB with the goal of enhancing transparency around supplier finance programs. On January 1, 2023, Ball adopted all required disclosures effective for 2023, on a retrospective basis. The company will adopt the rollforward disclosure requirements, on a prospective basis, when they become effective in 2024.\n\nThe company has several regional supplier finance programs, all of which have substantially similar characteristics, with various financial institutions that act as the paying agent for certain payables of the company. The company establishes these programs through agreements with the financial institutions to enable more efficient payment processing to our suppliers while also providing our suppliers a potential source of liquidity to the extent they enter into a factoring agreement with the financial institutions. Our suppliers’ participation in the programs is voluntary, and the company is not involved in negotiations of the suppliers’ arrangements with the financial institutions to sell their receivables, and our rights and obligations to our suppliers are not impacted by our suppliers’ decisions to sell amounts under these programs. Under these supplier finance programs, the company pays the financial institutions the stated amount of confirmed invoices from its participating suppliers on the original maturity dates of the invoices, which vary based on the negotiated terms with each supplier. All payment terms are short-term in nature and are not dependent on whether the suppliers participate in the supplier finance programs or if the suppliers elect to receive early payment from the financial institutions. Our supplier finance programs do not include any of the following: guarantees to the financial institutions, assets pledged as securities or interest accruing on the obligation prior to the due date.\n\nBased on the review of the facts and circumstances of our supplier finance programs, including but not limited to those noted above, the company has concluded that the characteristics of the obligations due under our supplier finance programs have not changed and remain those of standard accounts payables, rather than indicative of debt.\n\nThe amount of obligations outstanding that the company confirmed as valid to the financial institutions under the company's programs was $512 million and $930 million at September 30, 2023 and December 31, 2022, respectively. These amounts are classified within accounts payable on the unaudited condensed consolidated balance sheets, and the associated payments are reflected in the cash flows from operating activities section of the unaudited condensed consolidated statements of cash flows.\n\n3. Business Segment Information\n\nBall’s operations are organized and reviewed by management along its product lines and geographical areas and presented in the four reportable segments outlined below.\n\nBeverage packaging, North and Central America: Consists of operations in the U.S., Canada and Mexico that manufacture and sell aluminum beverage containers throughout those countries.\n\nBeverage packaging, EMEA: Consists of operations in numerous countries throughout Europe, as well as Egypt and Turkey, that manufacture and sell aluminum beverage containers throughout those countries. Ball sold its former operations located in Russia during the third quarter of 2022. See Note 4 for further details. Ball’s operations and results of its former Russian aluminum beverage packaging business are included in the results of the beverage packaging, EMEA, business through the date of the disposal in the third quarter of 2022.\n\n6\n[Chunk Index 14] Beverage packaging, South America: Consists of operations in Brazil, Argentina, Paraguay and Chile that manufacture and sell aluminum beverage containers throughout most of South America.\n\nAerospace: Consists of operations that manufacture and sell aerospace and other related products and provide services used in the defense, civil space and commercial space industries. In the third quarter of 2023, Ball entered into a Stock Purchase Agreement with BAE Systems, Inc., to sell all of the outstanding equity interests in Ball’s aerospace business to BAE. See Note 4 for further details.\n\nAs presented in the table below, Other consists of a non-reportable operating segment (beverage packaging, other) that manufactures and sells aluminum beverage containers in India, Saudi Arabia and throughout the Asia Pacific region; a non-reportable operating segment that manufactures and sells extruded aluminum aerosol containers and recloseable aluminum bottles across multiple consumer categories as well as aluminum slugs (aerosol packaging) throughout North America, South America, Europe, and Asia; a non-reportable operating segment that manufactures and sells aluminum cups (aluminum cups); undistributed corporate expenses; and intercompany eliminations and other business activities.\n\nThe accounting policies of the segments are the same as those used in the consolidated financial statements, as discussed in Note 1. The company also has investments in operations in Guatemala, Panama, the U.S. and Vietnam that are accounted for under the equity method of accounting and, accordingly, those results are not included in segment sales or earnings. In the first quarter of 2022, Ball sold its remaining equity method investment in Ball Metalpack. Refer to Note 4 for additional details.\n\n7\n[Chunk Index 15] Summary of Business by Segment\n[Chunk Index 16] ######Three Months Ended September 30,##########Nine Months Ended September 30,####\n($ in millions)####2023######2022####2023######2022\nNet sales####################\nBeverage packaging, North and Central America##$##1,541####$##1,800##$##4,582####$##5,184\nBeverage packaging, EMEA####902######1,031####2,656######3,106\nBeverage packaging, South America####489######466####1,344######1,494\nAerospace####460######477####1,467######1,471\nReportable segment sales####3,392######3,774####10,049######11,255\nOther####179######177####577######546\nNet sales##$##3,571####$##3,951##$##10,626####$##11,801\nComparable operating earnings####################\nBeverage packaging, North and Central America##$##196####$##205##$##554####$##543\nBeverage packaging, EMEA####103######82####274######311\nBeverage packaging, South America####61######67####141######197\nAerospace####46######47####160######126\nReportable segment comparable operating earnings####406######401####1,129######1,177\nReconciling items####################\nOther (a)####—######(8)####7######(26)\nBusiness consolidation and other activities####(47)######163####(61)######(23)\nAmortization of acquired intangibles####(34)######(33)####(102)######(102)\nEarnings before interest and taxes####325######523####973######1,026\nInterest expense####(122)######(79)####(350)######(216)\nDebt refinancing and other costs####—######—####—######(2)\nTotal interest expense####(122)######(79)####(350)######(218)\nEarnings before taxes##$##203####$##444##$##623####$##808\n[Chunk Index 17] (a) Includes undistributed corporate expenses, net, of $18 million and $25 million for the three months ended September 30, 2023 and 2022, respectively, and $60 million and $73 million for the nine months ended September 30, 2023 and 2022, respectively.\n\nThe company does not disclose total assets by segment as such information is not provided to the chief operating decision maker.\n\n4. Acquisitions and Dispositions\n\nAerospace\n\nIn the third quarter of 2023, Ball entered into a Stock Purchase Agreement (Agreement) with BAE Systems, Inc. (BAE) and, for the limited purposes set forth therein, BAE Systems plc, to sell all of the outstanding equity interests in Ball’s aerospace business to BAE for a purchase price of approximately $5.6 billi

In [ ]:
"""calculate max len of strings in df_chunk_eval["messages"][x][0]['content'] where x is row"""
max_len = 0
for x in range(len(df_chunk_eval)):
  if len(df_chunk_eval["messages"][x][0]['content']) > max_len:
    max_len = len(df_chunk_eval["messages"][x][0]['content'])
max_len

1050493

In [ ]:
i = df_chunk_eval["messages"][0][0]['content']
ranking_chunk = deepseek_model_chunks(system_prompt_chunk, i)
print(ranking_chunk)

<coroutine object deepseek_model_chunks at 0x7d0b11896d40>

In [ ]:
# convert string of a list to list
import ast
ast.literal_eval(ranking_chunk.choices[0].message.content)

[92, 93, 94, 95, 96, 97, 98, 99, 100, 101]

In [ ]:
print(ranking_chunk.choices[0].message.content)

[92, 93, 94, 95, 96, 97, 98, 99, 100, 101]

## Get Chunks ranking

In [ ]:
def create_chunk_prompt_top_k(question: str, chunks: List[str], chunk_indices: List[int], k: int = 10) -> str:
    """Ask model to select and rank only top-k most relevant chunks"""
    # Use k if chunks length > 10, else use chunks length
    actual_k = k if len(chunks) > 10 else len(chunks)

    prompt = f"""Identify the {actual_k} most relevant text chunks for answering this question, then rank them in order of relevance (best first).
Question: {question}
Text chunks:
"""
    for i, (chunk, orig_idx) in enumerate(zip(chunks, chunk_indices)):
        prompt += f"[Chunk Index {orig_idx}] {chunk}\n"
    prompt += f"""
Task: Select and rank the {actual_k} most relevant chunks among the given text chunks.
- Put the BEST chunk first
- Put the 2nd best chunk second
- Continue until you have ranked your top {actual_k} chunks
Response Format: [1st_most_relevant_index, 2nd_most_relevant_index, ..., {actual_k}th_most_relevant_index]"""

    return prompt

In [ ]:
async def process_chunk_ranking_two_stage(system_prompt, messages):
  """Process chunk ranking with multi-stage approach for high token count cases"""
  try:
      # Check if this is a high token case by examining the message content
      encoding = tiktoken.get_encoding("cl100k_base")
      # content = messages[0].get('content', '')
      content = messages
      token_count = len(encoding.encode(content))

      if token_count > 120000:

          # Extract question and chunks from the message content
          # Find question
          question_start = content.find('Question:')
          question_end = content.find('\n', question_start)
          if question_start != -1 and question_end != -1:
              question = content[question_start + len('Question:'):question_end].strip()
          else:
              question = None

          # Find chunks using regex-like pattern matching
          chunks = []
          chunk_indices = []

          import re
          # Pattern to match [Chunk Index N] followed by content until next [Chunk Index] or Task:
          chunk_pattern = r'\[Chunk Index (\d+)\]\s*([\s\S]*?)(?=\[Chunk Index|Task:|$)'
          matches = re.findall(chunk_pattern, content)

          for i, match in enumerate(matches):
              orig_idx = int(match[0])
              chunk_content = match[1].strip()

              # Clean up chunk content - remove any task instructions that might be caught
              if 'Task:' in chunk_content:
                  chunk_content = chunk_content.split('Task:')[0].strip()

              if chunk_content:
                  chunks.append(chunk_content)
                  chunk_indices.append(orig_idx)

          if not question or not chunks:
              print("⚠️ Could not parse question and chunks, falling back to normal processing")
              final_response = await deepseek_model_chunks(system_prompt, messages)
              # response = await get_model_response(messages, semaphore=semaphore)
              # predicted_ranking = extract_ranking_from_response(response, 10)
          else:
              # Split chunks into three parts
              third_point_1 = len(chunks) // 3
              third_point_2 = (len(chunks) * 2) // 3

              # First third
              first_third_chunks = chunks[:third_point_1]
              first_third_indices = chunk_indices[:third_point_1]
              first_prompt = create_chunk_prompt_top_k(question, first_third_chunks, first_third_indices, k=10)
              # first_messages = [{"role": "user", "content": first_prompt}]
              # first_response = await get_model_response(first_messages, semaphore=semaphore)
              first_top_3 = await deepseek_model_chunks(system_prompt, first_prompt)
              first_top_3 = ast.literal_eval(first_top_3.choices[0].message.content)
              # first_top_3 = extract_ranking_from_response(first_response, 10)

              # Second third
              second_third_chunks = chunks[third_point_1:third_point_2]
              second_third_indices = chunk_indices[third_point_1:third_point_2]
              second_prompt = create_chunk_prompt_top_k(question, second_third_chunks, second_third_indices, k=10)
              # second_messages = [{"role": "user", "content": second_prompt}]
              # second_response = await get_model_response(second_messages, semaphore=semaphore)
              second_top_3 = await deepseek_model_chunks(system_prompt, second_prompt)
              second_top_3 = ast.literal_eval(second_top_3.choices[0].message.content)
              # second_top_3 = extract_ranking_from_response(second_response, 10)

              # Third third
              third_third_chunks = chunks[third_point_2:]
              third_third_indices = chunk_indices[third_point_2:]
              third_prompt = create_chunk_prompt_top_k(question, third_third_chunks, third_third_indices, k=10)
              # third_messages = [{"role": "user", "content": third_prompt}]
              # third_response = await get_model_response(third_messages, semaphore=semaphore)
              third_top_4 = await deepseek_model_chunks(system_prompt, third_prompt)
              third_top_4 = ast.literal_eval(third_top_4.choices[0].message.content)
              # third_top_4 = extract_ranking_from_response(third_response, 10)

              # Combine top results from each third
              combined_indices = first_top_3 + second_top_3 + third_top_4
              combined_chunks = []

              # Get chunks for the combined indices while preserving original indices
              for idx in combined_indices:
                  if idx in chunk_indices:
                      chunk_pos = chunk_indices.index(idx)
                      combined_chunks.append(chunks[chunk_pos])

              final_prompt = create_chunk_prompt_top_k(question, combined_chunks, combined_indices, k=10)
              # final_messages = [{"role": "user", "content": final_prompt}]
              final_response = await deepseek_model_chunks(system_prompt, final_prompt) #, semaphore=semaphore)
              # predicted_ranking = extract_ranking_from_response(final_response, 10)

      else:
          # Normal single-stage processing
          final_response = await deepseek_model_chunks(system_prompt, messages) #, semaphore=semaphore)
          # predicted_ranking = extract_ranking_from_response(response, 10)

      return final_response
  except Exception as e:
      traceback.print_exc()
      print(f"❌ Error processing chunk ranking item: {e}")
      return []

In [ ]:
# results = pd.DataFrame(columns=['sample_id', 'target_index'])

In [ ]:
rankings_chunk = []
for i in range(115, len(df_chunk_eval)):
  prompt = df_chunk_eval["messages"][i][0]['content']
  ranking_chunk = await process_chunk_ranking_two_stage(system_prompt_chunk, prompt)
  current_rank_chunks = ast.literal_eval(ranking_chunk.choices[0].message.content)
  rankings_chunk.append(current_rank_chunks)

  if len(current_rank_chunks)<=5:
    current_rank_chunks = current_rank_chunks + [0]*(5-len(current_rank_chunks))

  print(current_rank_chunks)
  for j in current_rank_chunks[:5]:
    current_id = df_chunk_eval['_id'][i]
    chunk_rank = {'sample_id': current_id, 'target_index': j}
    # add chunk rank to df
    results = pd.concat([results, pd.DataFrame([chunk_rank])], ignore_index=True)

df_chunk_eval["rankings"] = rankings_chunk

[32, 33, 34, 35, 38, 39, 40, 89, 90, 114]
[7, 6, 9, 1, 16, 46, 47, 44, 45, 240]
[10, 2, 0, 9, 4, 11, 6, 8, 3, 7]
[5, 4, 6, 7, 24, 25, 26, 27, 28, 29]
[1, 0, 2, 27, 28, 29, 30, 31, 32, 33]
[4, 7, 9, 10, 11, 28, 30, 1, 8, 12]
[5, 7, 57, 67, 77, 91, 101, 107, 19, 35]
[67, 65, 66, 68, 69, 70, 71, 72, 64, 73]
[2, 3, 9, 8, 30, 31, 32, 33, 34, 35]
[75, 15, 142, 137, 138, 139, 140, 141, 0, 1]
[14, 15, 27, 33, 57, 59, 5, 7, 51, 13]
[194, 195, 196, 197, 198, 199, 115, 116, 117, 118]
[1, 107, 108, 109, 110, 111, 112, 113, 114, 115]
[60, 61, 128, 129, 7, 62, 63, 64, 65, 66]
[52, 53, 54, 55, 56, 57, 58, 59, 60, 61]
[101, 126, 55, 9, 144, 145, 146, 138, 139, 142]
[38, 42, 487, 486, 485, 39, 40, 43, 44, 41]
[1, 6, 4, 10, 5, 0, 2, 3, 7, 9]
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
[5, 7, 3, 4, 6, 122, 123, 124, 125, 0]
[15, 16, 17, 18, 1, 2, 4, 5, 6, 7]
[97, 96, 110, 111, 112, 101, 108, 185, 186, 98]
[43, 42, 41, 44, 45, 47, 48, 49, 50, 51]
[6, 7, 4, 1, 2, 3, 5, 0, 8, 9]
[0, 5, 15, 1, 37, 38, 45, 46, 48, 49]
[83, 89, 41, 23, 103, 57, 55, 99, 45, 93]
[5, 7, 17, 23, 25, 33, 37, 45, 47, 63]
[11, 12, 0, 3, 8, 16, 35, 37, 151, 153]
[194, 112, 117, 193, 113, 114, 119, 135, 134, 130]
[10, 175, 178, 180, 183, 186, 200, 205, 210, 213]
[3, 2, 1, 0, 4, 12, 16, 33, 32, 34]
[30, 35, 21, 26, 22, 25, 29, 33, 31, 23]
[2, 3, 6, 7, 15, 16, 17, 18, 19, 20]
[59, 60, 61, 62, 63, 64, 65, 66, 67, 68]
[64, 65, 66, 73, 74, 75, 76, 77, 78, 79]
[1, 5, 8, 21, 0, 3, 2, 4, 6, 7]
[9, 27, 26, 28, 29, 30, 31, 32, 33, 34]
[7, 5, 21, 15, 33, 45, 57, 63, 69, 91]
[111, 112, 113, 114, 115, 116, 117, 160, 161, 162]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
[125, 88, 87, 12, 11, 65, 66, 7, 235, 238]
[19, 25, 27, 40, 41, 64, 65, 72, 73, 102]
[37, 38, 39, 40, 41, 42, 43, 44, 45, 46]
[3, 11, 13, 45, 47, 95, 101, 125, 5, 57]
[5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
[3, 4, 1, 6, 7, 8, 9, 10, 11, 0]
[20, 22, 19, 16, 13, 11, 10, 9, 8, 122]
[3, 4, 0, 2, 1]
[9, 8, 101, 108, 107, 106, 105, 104, 100, 103]
[15, 20, 19, 16, 14, 17, 18, 13, 12, 21]
[63, 68, 64, 65, 66, 67, 69, 72, 73, 75]
[13, 30, 18, 14, 15, 17, 19, 20, 21, 23]
[32, 18, 38, 8, 33, 34, 35, 36, 37, 39]
[25, 5, 10, 3, 4, 24, 171, 138, 7, 8]
[31, 32, 34, 35, 36, 37, 38, 39, 40, 41]
[30, 95, 128, 129, 96, 125, 126, 127, 1, 5]
[5, 15, 21, 29, 79, 85, 101, 111, 3, 7]
[16, 14, 2, 1, 6, 5, 3, 17, 15, 0]
[12, 11, 10, 13, 14, 15, 16, 17, 18, 19]
[2, 12, 11, 30, 31, 32, 33, 34, 35, 36]
[21, 24, 23, 22, 25, 20, 26, 27, 18, 19]
[79, 80, 81, 85, 89, 90, 91, 92, 93, 94]
[16, 17, 18, 19, 20, 21, 22, 23, 12, 13]
[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
[64, 65, 66, 67, 68, 69, 70, 71, 72, 73]
[45, 44, 43, 42, 41, 40, 39, 38, 37, 36]
[3, 5, 13, 27, 37, 39, 49, 59, 71, 73]
[366, 367, 354, 355, 368, 370, 371, 372, 373, 39]
[40, 35, 36, 37, 38, 39, 41, 42, 43, 44]
[34, 33, 32, 35, 36, 37, 38, 39, 40, 41]
[1, 2, 0, 3, 4, 5, 6, 7, 8, 9]
[10, 2, 8, 9, 11, 6, 15, 20, 21, 25]
[9, 8, 4, 7, 2, 1, 0, 3, 5, 6]
[49, 50, 51, 90, 91, 89, 12, 13, 10, 94]
[112, 113, 114, 115, 116, 117, 118, 119, 120, 121]
[26, 27, 28, 56, 57, 58, 59, 60, 61, 72]
[14, 60, 6, 18, 19, 63, 64, 65, 67, 77]
[88, 89, 16, 91, 90, 17, 19, 86, 87, 123]
[28, 27, 29, 40, 41, 42, 43, 44, 45, 46]
[10, 9, 55, 40, 39, 11, 7, 33, 34, 35]
[4, 6, 17, 5, 7, 2, 0, 19, 11, 1]
[62, 63, 66, 67, 94, 95, 96, 97, 98, 100]
[137, 5, 11, 47, 97, 27, 61, 77, 103, 119]
[7, 3, 5, 9, 19, 45, 49, 69, 79, 89]
[17, 0, 23, 25, 16, 9, 8, 1, 3, 4]

ValueError: Length of values (85) does not match length of index (200)

In [ ]:
# Convert string to list of lists
ranking_lists_all = [ast.literal_eval(line) for line in ranking_list_temp.strip().splitlines() if line.strip()]

print(ranking_lists_all)

[[96, 98, 99, 100, 102, 103, 104, 106, 107, 108], [8, 9, 137, 138, 139, 140, 141, 142, 143, 144], [7, 5, 12, 45, 33, 19, 61, 67, 13, 15], [2, 3, 4, 5, 6, 7, 8, 181, 182, 1], [21, 22, 20, 6, 5, 1, 2, 3, 4, 7], [5, 7, 57, 113, 57, 5, 7, 113, 5, 7], [11, 17, 23, 29, 35, 43, 49, 55, 61, 67], [4, 1, 3, 5, 9, 6, 2, 0, 7, 8], [150, 149, 41, 230, 233, 231, 232, 234, 235, 236], [29, 30, 31, 32, 33, 34, 35, 36, 37, 38], [77, 76, 90, 89, 91, 56, 57, 78, 79, 80], [3, 2, 1, 4, 5, 6, 7, 8, 9, 10], [9, 66, 68, 16, 6, 8, 5, 2, 1, 15], [4, 20, 19, 24, 25, 3, 0, 1, 2, 5], [31, 30, 29, 28, 32, 33, 34, 35, 36, 37], [43, 44, 45, 46, 47, 48, 49, 50, 51, 52], [7, 5, 89, 87, 91, 93, 101, 103, 105, 107], [5, 7, 11, 57, 23, 27, 61, 67, 89, 101], [1, 3, 11, 9, 6, 12, 7, 4, 13, 2], [3, 1, 0, 2, 4], [17, 6, 5, 16, 15, 18, 19, 20, 21, 22], [10, 13, 16, 9, 12, 15, 14, 11, 18, 17], [253, 647, 4, 42, 64, 75, 237, 238, 252, 489], [3, 0, 23, 24, 25, 26, 27, 4, 1, 2], [16, 14, 13, 15, 11, 12, 1, 2, 10, 9], [86, 29, 30, 95, 96, 26, 92, 87, 3, 4], [2, 3, 4, 5, 6, 7, 8, 9, 10, 0], [34, 36, 37, 38, 39, 40, 41, 42, 46, 47], [99, 101, 103, 45, 47, 49, 79, 81, 23, 27], [1, 3, 0, 2, 12, 13, 7, 8, 9, 10], [37, 35, 36, 40, 39, 0, 1, 2, 3, 4], [13, 17, 23, 33, 43, 55, 65, 75, 85, 111], [29, 30, 31, 32, 33, 34, 35, 36, 37, 38], [41, 50, 51, 56, 57, 58, 59, 60, 61, 64], [11, 4, 3, 1, 45, 40, 39, 38, 37, 36], [7, 5, 3, 11, 13, 15, 17, 19, 21, 23], [13, 238, 244, 245, 242, 243, 241, 240, 239, 237], [2, 8, 9, 10, 1, 0, 3, 4, 7, 6], [19, 20, 21, 22, 23, 24, 25, 26, 27, 28], [1, 2, 11, 12, 46, 47, 48, 54, 55, 56], [45, 46, 47, 48, 49, 50, 51, 52, 53, 54], [17, 116, 119, 120, 121, 122, 123, 124, 125, 126], [0, 1, 2, 3, 4], [7, 20, 21, 11, 12, 15, 16, 17, 18, 19], [87, 88, 89, 116, 117, 118, 119, 120, 121, 122], [39, 40, 41, 42, 43, 44, 45, 46, 47, 48], [44, 32, 45, 46, 47, 48, 49, 50, 63, 70], [33, 59, 60, 62, 44, 42, 41, 39, 40, 37], [47, 48, 46, 49, 50, 51, 52, 53, 54, 55], [57, 56, 131, 130, 128, 132, 87, 127, 86, 83], [3, 0, 2, 1, 12, 18, 34, 37, 38, 6], [69, 33, 34, 36, 37, 38, 39, 40, 41, 42], [22, 23, 24, 25, 26, 27, 28, 29, 30, 31], [5, 7, 3, 13, 15, 23, 29, 39, 41, 45], [5, 7, 23, 41, 65, 47, 51, 35, 39, 61], [1, 3, 11, 4, 9, 6, 7, 8, 12, 13], [7, 5, 17, 23, 31, 45, 59, 81, 93, 71], [5, 85, 21, 73, 51, 53, 55, 61, 67, 81], [46, 45, 47, 59, 60, 61, 56, 57, 58, 44], [13, 15, 18, 19, 20, 21, 22, 23, 26, 27], [38, 39, 40, 53, 54, 55, 56, 57, 58, 59], [12, 13, 50, 51, 90, 94, 95, 9, 10, 5], [88, 89, 90, 91, 92, 93, 94, 95, 96, 97], [34, 61, 52, 58, 75, 86, 60, 64, 70, 72], [30, 31, 32, 33, 34, 35, 36, 37, 38, 39], [37, 38, 39, 40, 41, 42, 43, 44, 45, 46], [49, 50, 51, 52, 53, 54, 55, 56, 57, 58], [45, 46, 44, 48, 49, 50, 51, 52, 53, 47], [27, 349, 350, 381, 382, 26, 197, 18, 56, 57], [25, 5, 7, 9, 31, 33, 39, 45, 63, 65], [20, 21, 17, 18, 19, 1, 8, 9, 10, 11], [11, 12, 10, 9, 8, 7, 6, 5, 4, 3], [12, 25, 26, 28, 1, 3, 8, 10, 21, 23], [50, 12, 11, 10, 9, 8, 7, 6, 5, 4], [15, 16, 17, 18, 19, 20, 21, 22, 23, 24], [13, 3, 5, 9, 11, 7, 15, 17, 19, 21], [7, 5, 9, 13, 15, 19, 21, 23, 25, 27], [89, 90, 91, 92, 93, 94, 95, 96, 97, 98], [55, 8, 60, 61, 69, 68, 67, 66, 65, 64], [90, 91, 92, 94, 95, 96, 97, 98, 99, 100], [73, 126, 142, 125, 92, 94, 95, 110, 111, 112], [85, 27, 25, 87, 26, 43, 45, 5, 29, 33], [66, 67, 65, 64, 10, 11, 9, 8, 7, 6], [49, 48, 47, 46, 45, 44, 43, 42, 41, 40], [16, 18, 17, 19, 15, 14, 22, 20, 21, 23], [137, 138, 139, 140, 141, 142, 143, 144, 145, 146], [3, 4, 33, 35, 36, 37, 38, 39, 40, 41], [9, 10, 7, 6, 0, 2, 1, 3, 4, 5], [1, 0, 7, 6, 8, 9, 10, 11, 12, 13], [3, 9, 12, 13, 23, 49, 53, 59, 63, 2], [0, 1, 33, 34, 59, 61, 62, 64, 65, 66], [26, 27, 28, 29, 30, 31, 32, 33, 34, 35], [6, 5, 4, 7, 8, 3, 2, 1, 0, 9], [5, 7, 45, 51, 67, 69, 17, 19, 33, 57], [12, 16, 108, 55, 56, 57, 58, 59, 60, 61], [69, 68, 27, 70, 29, 4, 0, 1, 2, 3], [14, 15, 16, 17, 18, 19, 20, 21, 22, 23], [37, 38, 39, 42, 43, 36, 34, 45, 46, 48], [7, 5, 4, 6, 3, 8, 9, 10, 11, 12], [58, 59, 61, 62, 57, 56, 60, 52, 19, 64], [48, 49, 42, 43, 44, 45, 46, 47, 73, 50], [5, 7, 3, 9, 19, 21, 23, 25, 33, 37], [17, 19, 16, 18, 6, 7, 63, 64, 65, 4], [41, 42, 43, 44, 45, 46, 47, 48, 49, 50], [9, 7, 6, 8, 0, 2, 5, 17, 20, 4], [23, 24, 25, 26, 27, 28, 29, 30, 31, 32], [144, 145, 143, 142, 141, 140, 139, 138, 137, 136], [5, 63, 62, 65, 43, 42, 64, 77, 14, 15], [31, 32, 33, 34, 35, 36, 37, 38, 39, 40], [47, 48, 49, 50, 51, 52, 53, 54, 55, 56], [3, 8, 2, 9, 18, 11, 15, 19, 20, 23], [13, 12, 14, 58, 59, 60, 61, 62, 63, 64], [181, 120, 117, 114, 115, 116, 118, 119, 121, 122], [23, 24, 25, 26, 27, 28, 29, 30, 31, 32], [0, 1, 2, 3, 4], [32, 33, 34, 35, 38, 39, 40, 89, 90, 114], [7, 6, 9, 1, 16, 46, 47, 44, 45, 240], [10, 2, 0, 9, 4, 11, 6, 8, 3, 7], [5, 4, 6, 7, 24, 25, 26, 27, 28, 29], [1, 0, 2, 27, 28, 29, 30, 31, 32, 33], [4, 7, 9, 10, 11, 28, 30, 1, 8, 12], [5, 7, 57, 67, 77, 91, 101, 107, 19, 35], [67, 65, 66, 68, 69, 70, 71, 72, 64, 73], [2, 3, 9, 8, 30, 31, 32, 33, 34, 35], [75, 15, 142, 137, 138, 139, 140, 141, 0, 1], [14, 15, 27, 33, 57, 59, 5, 7, 51, 13], [194, 195, 196, 197, 198, 199, 115, 116, 117, 118], [1, 107, 108, 109, 110, 111, 112, 113, 114, 115], [60, 61, 128, 129, 7, 62, 63, 64, 65, 66], [52, 53, 54, 55, 56, 57, 58, 59, 60, 61], [101, 126, 55, 9, 144, 145, 146, 138, 139, 142], [38, 42, 487, 486, 485, 39, 40, 43, 44, 41], [1, 6, 4, 10, 5, 0, 2, 3, 7, 9], [6, 7, 8, 9, 10, 11, 12, 13, 14, 15], [5, 7, 3, 4, 6, 122, 123, 124, 125, 0], [15, 16, 17, 18, 1, 2, 4, 5, 6, 7], [97, 96, 110, 111, 112, 101, 108, 185, 186, 98], [43, 42, 41, 44, 45, 47, 48, 49, 50, 51], [6, 7, 4, 1, 2, 3, 5, 0, 8, 9], [0, 5, 15, 1, 37, 38, 45, 46, 48, 49], [83, 89, 41, 23, 103, 57, 55, 99, 45, 93], [5, 7, 17, 23, 25, 33, 37, 45, 47, 63], [11, 12, 0, 3, 8, 16, 35, 37, 151, 153], [194, 112, 117, 193, 113, 114, 119, 135, 134, 130], [10, 175, 178, 180, 183, 186, 200, 205, 210, 213], [3, 2, 1, 0, 4, 12, 16, 33, 32, 34], [30, 35, 21, 26, 22, 25, 29, 33, 31, 23], [2, 3, 6, 7, 15, 16, 17, 18, 19, 20], [59, 60, 61, 62, 63, 64, 65, 66, 67, 68], [64, 65, 66, 73, 74, 75, 76, 77, 78, 79], [1, 5, 8, 21, 0, 3, 2, 4, 6, 7], [9, 27, 26, 28, 29, 30, 31, 32, 33, 34], [7, 5, 21, 15, 33, 45, 57, 63, 69, 91], [111, 112, 113, 114, 115, 116, 117, 160, 161, 162], [9, 8, 7, 6, 5, 4, 3, 2, 1, 0], [125, 88, 87, 12, 11, 65, 66, 7, 235, 238], [19, 25, 27, 40, 41, 64, 65, 72, 73, 102], [37, 38, 39, 40, 41, 42, 43, 44, 45, 46], [3, 11, 13, 45, 47, 95, 101, 125, 5, 57], [5, 6, 7, 8, 9, 10, 11, 12, 13, 14], [3, 4, 1, 6, 7, 8, 9, 10, 11, 0], [20, 22, 19, 16, 13, 11, 10, 9, 8, 122], [3, 4, 0, 2, 1], [9, 8, 101, 108, 107, 106, 105, 104, 100, 103], [15, 20, 19, 16, 14, 17, 18, 13, 12, 21], [63, 68, 64, 65, 66, 67, 69, 72, 73, 75], [13, 30, 18, 14, 15, 17, 19, 20, 21, 23], [32, 18, 38, 8, 33, 34, 35, 36, 37, 39], [25, 5, 10, 3, 4, 24, 171, 138, 7, 8], [31, 32, 34, 35, 36, 37, 38, 39, 40, 41], [30, 95, 128, 129, 96, 125, 126, 127, 1, 5], [5, 15, 21, 29, 79, 85, 101, 111, 3, 7], [16, 14, 2, 1, 6, 5, 3, 17, 15, 0], [12, 11, 10, 13, 14, 15, 16, 17, 18, 19], [2, 12, 11, 30, 31, 32, 33, 34, 35, 36], [21, 24, 23, 22, 25, 20, 26, 27, 18, 19], [79, 80, 81, 85, 89, 90, 91, 92, 93, 94], [16, 17, 18, 19, 20, 21, 22, 23, 12, 13], [5, 5, 5, 5, 5, 5, 5, 5, 5, 5], [64, 65, 66, 67, 68, 69, 70, 71, 72, 73], [45, 44, 43, 42, 41, 40, 39, 38, 37, 36], [3, 5, 13, 27, 37, 39, 49, 59, 71, 73], [366, 367, 354, 355, 368, 370, 371, 372, 373, 39], [40, 35, 36, 37, 38, 39, 41, 42, 43, 44], [34, 33, 32, 35, 36, 37, 38, 39, 40, 41], [1, 2, 0, 3, 4, 5, 6, 7, 8, 9], [10, 2, 8, 9, 11, 6, 15, 20, 21, 25], [9, 8, 4, 7, 2, 1, 0, 3, 5, 6], [49, 50, 51, 90, 91, 89, 12, 13, 10, 94], [112, 113, 114, 115, 116, 117, 118, 119, 120, 121], [26, 27, 28, 56, 57, 58, 59, 60, 61, 72], [14, 60, 6, 18, 19, 63, 64, 65, 67, 77], [88, 89, 16, 91, 90, 17, 19, 86, 87, 123], [28, 27, 29, 40, 41, 42, 43, 44, 45, 46], [10, 9, 55, 40, 39, 11, 7, 33, 34, 35], [4, 6, 17, 5, 7, 2, 0, 19, 11, 1], [62, 63, 66, 67, 94, 95, 96, 97, 98, 100], [137, 5, 11, 47, 97, 27, 61, 77, 103, 119], [7, 3, 5, 9, 19, 45, 49, 69, 79, 89], [17, 0, 23, 25, 16, 9, 8, 1, 3, 4]]

In [ ]:
len(ranking_lists_all)

200

In [ ]:
results = pd.DataFrame(columns=['sample_id', 'target_index'])


for index, i in enumerate(ranking_lists_all):
  if len(i)<=5:
      i = i + [0]*(5-len(i))

  # print(i)
  for j in i[:5]:
    current_id = df_chunk_eval['_id'][index]
    chunk_rank = {'sample_id': current_id, 'target_index': j}
    # add chunk rank to df
    results = pd.concat([results, pd.DataFrame([chunk_rank])], ignore_index=True)

In [ ]:
results

         sample_id target_index
0    chunk_q613509           96
1    chunk_q613509           98
2    chunk_q613509           99
3    chunk_q613509          100
4    chunk_q613509          102
..             ...          ...
995  chunk_qa1d2bd           17
996  chunk_qa1d2bd            0
997  chunk_qa1d2bd           23
998  chunk_qa1d2bd           25
999  chunk_qa1d2bd           16

[1000 rows x 2 columns]

In [ ]:
# save results with chunks
results.to_csv('results_chunks.csv', index=False)

In [ ]:
# join results.csv and results_chunks.csv
df_results = pd.read_csv('results.csv')

# change ranking col to target_index
df_results = df_results.rename(columns={'rankings': 'target_index'}, inplace=False)
df_results_chunks = pd.read_csv('results_chunks.csv')

# join
df_results_all = pd.concat([df_results, df_results_chunks], ignore_index=True)

In [ ]:
df_results_all.to_csv('results_all.csv', index=False)